import { Exercise } from "./types";

// ── Bit Manipulation Exercises ────────────────────────────────────────────────
export const BIT_EXERCISES: Exercise[] = [
  {
    id: "count-set-bits",
    tier: 2, category: "bit-manipulation",
    title: "Count Set Bits (Hamming Weight)",
    tagline: "How many 1-bits are in this integer?",
    description: "Write `hammingWeight(n)` that returns the number of '1' bits in the binary representation of the unsigned 32-bit integer `n`. Do not convert to a string.",
    why: "Bit counting appears in cryptography, error correction, hardware design, and compression algorithms. Understanding it forces you to think below the level of numbers — at the level of individual bits.",
    analogy: "You're tallying how many light switches are flipped ON in a panel of 32. Each switch is a bit; you need the count of ON switches.",
    examples: [
      { input: "hammingWeight(11)", output: "3", note: "11 = 0b1011 — three 1-bits" },
      { input: "hammingWeight(128)", output: "1", note: "128 = 0b10000000 — one 1-bit" },
      { input: "hammingWeight(4294967293)", output: "31", note: "0b11111111111111111111111111111101" },
    ],
    starterCode: `function hammingWeight(n) {\n  // don't use n.toString(2) — use bit operations\n}`,
    functionName: "hammingWeight",
    testCases: [
      { args: [11], expected: 3, label: "11 (1011) → 3" },
      { args: [128], expected: 1, label: "128 (10000000) → 1" },
      { args: [0], expected: 0, label: "0 → 0" },
      { args: [2147483645], expected: 30, label: "30 set bits", hidden: true },
      { args: [1], expected: 1, label: "1 (0001) → 1", hidden: true },
    ],
    solution: `function hammingWeight(n) {\n  let count = 0;\n  while (n !== 0) {\n    count += n & 1;\n    n >>>= 1;\n  }\n  return count;\n}`,
    solutionExplanation: "Check the least significant bit with `n & 1`. Unsigned right-shift (`>>>=1`) moves to the next bit without sign extension. Repeat until n is 0. The Brian Kernighan trick (n &= n-1) clears the lowest set bit each iteration and is even faster.",
    hints: ["n & 1 gives you the rightmost bit", ">>> is unsigned right shift — use it instead of >> to avoid sign extension on negative numbers", "Loop until n === 0"],
    tags: ["bits", "AND", "shift"], estimatedMinutes: 10,
  },
  {
    id: "is-power-of-two",
    tier: 1, category: "bit-manipulation",
    title: "Power of Two",
    tagline: "One line. One trick.",
    description: "Write `isPowerOfTwo(n)` that returns `true` if `n` is a power of two. Do not use loops or recursion — solve it with a single bit operation.",
    why: "The n & (n-1) trick is the most famous bit manipulation technique. Powers of 2 in binary have exactly one '1' bit. Understanding why this works builds intuition for all bit tricks.",
    analogy: "Powers of 2 look like 1, 10, 100, 1000 in binary. Subtracting 1 gives 0, 01, 011, 0111. AND-ing them gives 0 for all powers of 2.",
    examples: [
      { input: "isPowerOfTwo(1)", output: "true", note: "2^0 = 1" },
      { input: "isPowerOfTwo(16)", output: "true", note: "2^4 = 16" },
      { input: "isPowerOfTwo(6)", output: "false", note: "6 = 110 — two bits set" },
      { input: "isPowerOfTwo(0)", output: "false" },
    ],
    starterCode: `function isPowerOfTwo(n) {\n  // single bit operation — no loops\n}`,
    functionName: "isPowerOfTwo",
    testCases: [
      { args: [1], expected: true, label: "1 = 2^0 → true" },
      { args: [16], expected: true, label: "16 = 2^4 → true" },
      { args: [6], expected: false, label: "6 = 0b110 → false" },
      { args: [0], expected: false, label: "0 → false" },
      { args: [1024], expected: true, label: "1024 = 2^10 → true" },
      { args: [3], expected: false, label: "3 = 0b11 → false", hidden: true },
    ],
    solution: `function isPowerOfTwo(n) {\n  return n > 0 && (n & (n - 1)) === 0;\n}`,
    solutionExplanation: "A power of 2 has exactly one '1' bit. n-1 flips that bit and sets all lower bits. ANDing n with n-1 clears the lowest '1' bit — if there was only one, the result is 0. Guard against n=0 separately.",
    hints: ["Powers of 2 in binary: 1, 10, 100, 1000...", "n-1 for a power of 2: 0, 01, 011, 0111...", "n & (n-1) clears the lowest set bit"],
    tags: ["bits", "AND", "O(1)"], estimatedMinutes: 8,
  },
  {
    id: "single-number",
    tier: 2, category: "bit-manipulation",
    title: "Single Number",
    tagline: "XOR finds the odd one out.",
    description: "Write `singleNumber(nums)` where every element appears exactly twice except for one. Find and return the one that appears only once. Solve in O(n) time and O(1) space — no hash map.",
    why: "XOR is the most elegant bit trick: a ^ a = 0, and a ^ 0 = a. XOR-ing all elements cancels pairs, leaving only the unique element. This teaches you to look for mathematical properties that eliminate the need for data structures.",
    analogy: "Pair up everyone in the room — each pair cancels. The person with no partner is the answer.",
    examples: [
      { input: "singleNumber([2,2,1])", output: "1" },
      { input: "singleNumber([4,1,2,1,2])", output: "4" },
      { input: "singleNumber([1])", output: "1" },
    ],
    starterCode: `function singleNumber(nums) {\n  // no hash map — use XOR\n}`,
    functionName: "singleNumber",
    testCases: [
      { args: [[2, 2, 1]], expected: 1, label: "[2,2,1] → 1" },
      { args: [[4, 1, 2, 1, 2]], expected: 4, label: "[4,1,2,1,2] → 4" },
      { args: [[1]], expected: 1, label: "[1] → 1" },
      { args: [[1, 1, 2, 2, 3]], expected: 3, label: "[1,1,2,2,3] → 3", hidden: true },
    ],
    solution: `function singleNumber(nums) {\n  return nums.reduce((xor, n) => xor ^ n, 0);\n}`,
    solutionExplanation: "XOR every number together. a ^ a = 0, so every pair cancels out. a ^ 0 = a, so what's left is the unique number. Order doesn't matter — XOR is commutative and associative.",
    hints: ["a XOR a = 0", "a XOR 0 = a", "XOR everything together — pairs cancel, lone number survives"],
    tags: ["bits", "XOR", "O(1)-space"], estimatedMinutes: 10,
  },
  {
    id: "missing-number",
    tier: 2, category: "bit-manipulation",
    title: "Missing Number",
    tagline: "Find the gap in 0 to n.",
    description: "Write `missingNumber(nums)` that takes an array of `n` distinct numbers in the range `[0, n]` and returns the one number that is missing. Solve in O(1) space without sorting.",
    why: "There are two elegant solutions: XOR (bit manipulation) and the Gauss sum formula (math). Both are O(n) time, O(1) space. Knowing two ways to solve the same problem builds pattern recognition.",
    examples: [
      { input: "missingNumber([3,0,1])", output: "2" },
      { input: "missingNumber([0,1])", output: "2" },
      { input: "missingNumber([9,6,4,2,3,5,7,0,1])", output: "8" },
    ],
    starterCode: `function missingNumber(nums) {\n  // Gauss sum: expected sum - actual sum\n  // or: XOR all indices and all values\n}`,
    functionName: "missingNumber",
    testCases: [
      { args: [[3, 0, 1]], expected: 2, label: "[3,0,1] → 2" },
      { args: [[0, 1]], expected: 2, label: "[0,1] → 2" },
      { args: [[9, 6, 4, 2, 3, 5, 7, 0, 1]], expected: 8, label: "9 elements, missing 8" },
      { args: [[0]], expected: 1, label: "[0] → 1", hidden: true },
    ],
    solution: `function missingNumber(nums) {\n  const n = nums.length;\n  const expected = (n * (n + 1)) / 2;\n  return expected - nums.reduce((s, x) => s + x, 0);\n}`,
    solutionExplanation: "The sum of 0..n is n*(n+1)/2 by Gauss's formula. Subtract the actual sum of the array — the difference is the missing number. Alternatively: XOR all indices 0..n with all array values — pairs cancel, missing number remains.",
    hints: ["Gauss: sum of 0..n = n*(n+1)/2", "expected sum - actual sum = missing number", "Bonus: the XOR approach works too — XOR all indices and values"],
    tags: ["bits", "math", "XOR"], estimatedMinutes: 10,
  },
  {
    id: "reverse-bits",
    tier: 3, category: "bit-manipulation",
    title: "Reverse Bits",
    tagline: "Mirror the 32 bits of an unsigned integer.",
    description: "Write `reverseBits(n)` that reverses the bits of a 32-bit unsigned integer. The least significant bit becomes the most significant bit.",
    why: "Bit reversal is used in the Fast Fourier Transform, cryptographic algorithms, and hardware interfaces. Building it forces you to understand bit shifting and masking precisely.",
    analogy: "You have a row of 32 light switches. Mirror the row: switch 1 becomes switch 32, switch 2 becomes switch 31, and so on.",
    examples: [
      { input: "reverseBits(43261596)", output: "964176192", note: "0b00000010100101000001111010011100 → 0b00111001011110000010100101000000" },
      { input: "reverseBits(4294967293)", output: "3221225471", note: "0b11111111111111111111111111111101 → 0b10111111111111111111111111111111" },
    ],
    starterCode: `function reverseBits(n) {\n  // build the reversed number bit by bit\n}`,
    functionName: "reverseBits",
    testCases: [
      { args: [43261596], expected: 964176192, label: "43261596 → 964176192" },
      { args: [4294967293], expected: 3221225471, label: "4294967293 → 3221225471" },
      { args: [0], expected: 0, label: "0 → 0", hidden: true },
      { args: [1], expected: 2147483648, label: "1 → 2^31", hidden: true },
    ],
    solution: `function reverseBits(n) {\n  let result = 0;\n  for (let i = 0; i < 32; i++) {\n    result = (result * 2) + (n & 1);\n    n >>>= 1;\n  }\n  return result >>> 0; // ensure unsigned 32-bit\n}`,
    solutionExplanation: "Build the result bit by bit from LSB to MSB. Each iteration: extract LSB with (n & 1), shift it into the result by multiplying by 2 (left shift), then unsigned right shift n. `>>> 0` at the end ensures the result is treated as unsigned.",
    hints: ["Extract the rightmost bit with n & 1", "Shift result left (×2) and add the extracted bit", "Use >>> instead of >> to handle unsigned correctly", ">>> 0 at the end forces unsigned 32-bit integer"],
    tags: ["bits", "shift", "mask"], estimatedMinutes: 15,
  },
];
