import { Exercise } from "./types";

// ── Dynamic Programming Exercises ─────────────────────────────────────────────
export const DP_EXERCISES: Exercise[] = [
  {
    id: "coin-change",
    tier: 4, category: "dynamic-programming",
    title: "Coin Change",
    tagline: "Fewest coins to make the amount.",
    description: "Write `coinChange(coins, amount)` that returns the minimum number of coins needed to make `amount`. Return `-1` if it's impossible. You have unlimited copies of each coin.",
    why: "Coin Change is the DP gateway drug. It teaches you bottom-up tabulation: build the solution for every smaller sub-problem before tackling the big one.",
    analogy: "You're a cashier making change. Instead of grabbing random coins, you work out the optimal number of coins for every amount from $0 to the target, building up your answer table.",
    examples: [
      { input: "coinChange([1,5,11], 15)", output: "3", note: "11+3×1 = 14... no. 11+4 = 15. Or 5+5+5=15 (3 coins). Or 15×1=15 (15 coins). Best is 3." },
      { input: "coinChange([1,5,11], 16)", output: "2", note: "11+5=16" },
      { input: "coinChange([2], 3)", output: "-1", note: "impossible" },
    ],
    starterCode: `function coinChange(coins, amount) {\n  // bottom-up DP\n  // dp[i] = min coins to make amount i\n}`,
    functionName: "coinChange",
    testCases: [
      { args: [[1, 5, 11], 15], expected: 3, label: "coins=[1,5,11], amount=15 → 3 (5+5+5)" },
      { args: [[1, 5, 11], 16], expected: 2, label: "coins=[1,5,11], amount=16 → 2 (11+5)" },
      { args: [[2], 3], expected: -1, label: "impossible → -1" },
      { args: [[1, 2, 5], 11], expected: 3, label: "coins=[1,2,5], 11 → 3 (5+5+1)" },
      { args: [[1], 0], expected: 0, label: "amount=0 → 0 coins", hidden: true },
      { args: [[186, 419, 83, 408], 6249], expected: 20, label: "larger case", hidden: true },
    ],
    solution: `function coinChange(coins, amount) {\n  const dp = new Array(amount + 1).fill(Infinity);\n  dp[0] = 0;\n  for (let i = 1; i <= amount; i++) {\n    for (const coin of coins) {\n      if (coin <= i) dp[i] = Math.min(dp[i], dp[i - coin] + 1);\n    }\n  }\n  return dp[amount] === Infinity ? -1 : dp[amount];\n}`,
    solutionExplanation: "Create dp array of size amount+1, initialized to Infinity (impossible). dp[0]=0 (base case). For every amount from 1 to target, try every coin: dp[i] = min(dp[i], dp[i-coin]+1). If dp[amount] is still Infinity, it's impossible.",
    hints: ["dp[i] = minimum coins to make exactly amount i", "dp[0] = 0 (base case), all others start at Infinity", "For each amount, try every coin: if dp[i - coin] + 1 < dp[i], update it"],
    tags: ["DP", "tabulation", "optimization"], estimatedMinutes: 25,
  },
  {
    id: "longest-common-subsequence",
    tier: 4, category: "dynamic-programming",
    title: "Longest Common Subsequence",
    tagline: "The longest sequence that appears in both strings.",
    description: "Write `lcs(text1, text2)` that returns the length of the longest common subsequence. A subsequence doesn't need to be contiguous — just in order.",
    why: "LCS is the algorithm behind `git diff`, DNA comparison, and spell checkers. It's the prototypical 2D DP problem — solving it gives you the mental model for dozens of other problems.",
    analogy: "Given 'ABCDE' and 'ACE': you can pull out 'ACE' from both in order — length 3. That's the LCS.",
    examples: [
      { input: "lcs('abcde', 'ace')", output: "3", note: "LCS is 'ace'" },
      { input: "lcs('abc', 'abc')", output: "3", note: "identical" },
      { input: "lcs('abc', 'def')", output: "0", note: "nothing in common" },
    ],
    starterCode: `function lcs(text1, text2) {\n  // build a 2D dp table\n  // dp[i][j] = LCS of text1[0..i-1] and text2[0..j-1]\n}`,
    functionName: "lcs",
    testCases: [
      { args: ["abcde", "ace"], expected: 3, label: "'abcde','ace' → 3" },
      { args: ["abc", "abc"], expected: 3, label: "identical strings → 3" },
      { args: ["abc", "def"], expected: 0, label: "no common chars → 0" },
      { args: ["oxcpqrsvwf", "shmtulqrypy"], expected: 2, label: "longer strings", hidden: true },
      { args: ["", "abc"], expected: 0, label: "empty string → 0", hidden: true },
    ],
    solution: `function lcs(text1, text2) {\n  const m = text1.length, n = text2.length;\n  const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));\n  for (let i = 1; i <= m; i++) {\n    for (let j = 1; j <= n; j++) {\n      if (text1[i-1] === text2[j-1]) dp[i][j] = dp[i-1][j-1] + 1;\n      else dp[i][j] = Math.max(dp[i-1][j], dp[i][j-1]);\n    }\n  }\n  return dp[m][n];\n}`,
    solutionExplanation: "Build a (m+1)×(n+1) table. If characters match: dp[i][j] = dp[i-1][j-1]+1 (extend the LCS). Otherwise: dp[i][j] = max(dp[i-1][j], dp[i][j-1]) (take the best from either direction).",
    hints: ["Build a 2D dp table where dp[i][j] = LCS length using text1[0..i-1] and text2[0..j-1]", "If text1[i-1] === text2[j-1]: we extend the diagonal", "Otherwise: take the max of dp[i-1][j] and dp[i][j-1]"],
    tags: ["DP", "2D-DP", "strings"], estimatedMinutes: 25,
  },
  {
    id: "word-break",
    tier: 4, category: "dynamic-programming",
    title: "Word Break",
    tagline: "Can this string be cut into dictionary words?",
    description: "Write `wordBreak(s, wordDict)` that returns `true` if `s` can be segmented into one or more words from `wordDict`.",
    why: "Word break is how search engines handle queries with no spaces, how text prediction works, and how compilers tokenize input. The DP solution models a fundamental pattern: 'can I reach this position?'",
    analogy: "You're cutting a ribbon into pieces, and each piece must match a word in the dictionary. Can you cut it up so that every piece matches?",
    examples: [
      { input: "wordBreak('leetcode', ['leet','code'])", output: "true", note: "'leet' + 'code'" },
      { input: "wordBreak('applepenapple', ['apple','pen'])", output: "true", note: "'apple'+'pen'+'apple'" },
      { input: "wordBreak('catsandog', ['cats','dog','sand','and','cat'])", output: "false" },
    ],
    starterCode: `function wordBreak(s, wordDict) {\n  // dp[i] = can s[0..i-1] be segmented?\n}`,
    functionName: "wordBreak",
    testCases: [
      { args: ["leetcode", ["leet", "code"]], expected: true, label: "'leet'+'code' → true" },
      { args: ["applepenapple", ["apple", "pen"]], expected: true, label: "'apple'+'pen'+'apple' → true" },
      { args: ["catsandog", ["cats", "dog", "sand", "and", "cat"]], expected: false, label: "can't complete → false" },
      { args: ["ab", ["a", "b"]], expected: true, label: "single chars → true", hidden: true },
      { args: ["a", ["b"]], expected: false, label: "no match → false", hidden: true },
    ],
    solution: `function wordBreak(s, wordDict) {\n  const words = new Set(wordDict);\n  const dp = new Array(s.length + 1).fill(false);\n  dp[0] = true;\n  for (let i = 1; i <= s.length; i++) {\n    for (let j = 0; j < i; j++) {\n      if (dp[j] && words.has(s.slice(j, i))) {\n        dp[i] = true;\n        break;\n      }\n    }\n  }\n  return dp[s.length];\n}`,
    solutionExplanation: "dp[i] means 'can s[0..i-1] be segmented?' dp[0]=true (empty string). For each position i, check every split point j: if dp[j] is true AND s[j..i] is a word, then dp[i]=true.",
    hints: ["dp[i] = can s[0..i-1] be broken into words?", "dp[0] = true (empty string is always valid)", "For each i, try every cut point j: if dp[j] is true and s[j..i] is in the dict, dp[i] = true"],
    tags: ["DP", "string", "set"], estimatedMinutes: 20,
  },
  {
    id: "longest-increasing-subsequence",
    tier: 4, category: "dynamic-programming",
    title: "Longest Increasing Subsequence",
    tagline: "Find the longest strictly increasing sub-sequence.",
    description: "Write `lis(nums)` that returns the length of the longest strictly increasing subsequence. A subsequence doesn't need to be contiguous.",
    why: "LIS appears in patience sorting, stock trading strategies, and sequence analysis. The O(n²) DP approach teaches the 'build on previous results' pattern; the O(n log n) approach is a bonus challenge.",
    analogy: "You're picking cards from a deck in order. You can only pick a card if it's higher than the last one you picked. What's the most cards you can collect?",
    examples: [
      { input: "lis([10,9,2,5,3,7,101,18])", output: "4", note: "[2,5,7,101]" },
      { input: "lis([0,1,0,3,2,3])", output: "4", note: "[0,1,2,3]" },
      { input: "lis([7,7,7,7])", output: "1", note: "strictly increasing, so no repeats" },
    ],
    starterCode: `function lis(nums) {\n  // dp[i] = length of LIS ending at index i\n}`,
    functionName: "lis",
    testCases: [
      { args: [[10, 9, 2, 5, 3, 7, 101, 18]], expected: 4, label: "[10,9,2,5,3,7,101,18] → 4" },
      { args: [[0, 1, 0, 3, 2, 3]], expected: 4, label: "[0,1,0,3,2,3] → 4" },
      { args: [[7, 7, 7, 7]], expected: 1, label: "all same → 1" },
      { args: [[1]], expected: 1, label: "single element → 1", hidden: true },
      { args: [[1, 2, 3, 4, 5]], expected: 5, label: "already sorted → 5", hidden: true },
    ],
    solution: `function lis(nums) {\n  const dp = new Array(nums.length).fill(1);\n  let max = 1;\n  for (let i = 1; i < nums.length; i++) {\n    for (let j = 0; j < i; j++) {\n      if (nums[j] < nums[i]) dp[i] = Math.max(dp[i], dp[j] + 1);\n    }\n    max = Math.max(max, dp[i]);\n  }\n  return max;\n}`,
    solutionExplanation: "dp[i] = length of the LIS ending at index i. Initialize all to 1 (every element alone is a valid LIS). For each i, look back at every j < i: if nums[j] < nums[i], we can extend the LIS ending at j. Track the running max.",
    hints: ["dp[i] = length of LIS ending at position i", "For each i, look at every j before it: if nums[j] < nums[i], then dp[i] = max(dp[i], dp[j]+1)", "The answer is max(dp)"],
    tags: ["DP", "LIS", "patience-sorting"], estimatedMinutes: 20,
  },
  {
    id: "zero-one-knapsack",
    tier: 4, category: "dynamic-programming",
    title: "0/1 Knapsack",
    tagline: "Max value without exceeding weight capacity.",
    description: "Write `knapsack(weights, values, capacity)` that returns the maximum total value you can fit in a knapsack of the given capacity. You can use each item at most once.",
    why: "Knapsack is in every CS curriculum because it perfectly illustrates the DP pattern of optimal substructure. It powers resource allocation, portfolio optimization, and budget planning algorithms.",
    analogy: "You're packing a backpack for a hike. Each item has a weight and a value. You have a weight limit. What's the most valuable load you can carry without going over?",
    examples: [
      { input: "knapsack([2,3,4,5], [3,4,5,6], 5)", output: "7", note: "items with weight 2 (val 3) + weight 3 (val 4)" },
      { input: "knapsack([1,3,4,5], [1,4,5,7], 7)", output: "9", note: "weight 3 (val 4) + weight 4 (val 5)" },
    ],
    starterCode: `function knapsack(weights, values, capacity) {\n  // dp[i][w] = max value using first i items with weight limit w\n}`,
    functionName: "knapsack",
    testCases: [
      { args: [[2, 3, 4, 5], [3, 4, 5, 6], 5], expected: 7, label: "capacity 5 → 7" },
      { args: [[1, 3, 4, 5], [1, 4, 5, 7], 7], expected: 9, label: "capacity 7 → 9" },
      { args: [[5], [10], 3], expected: 0, label: "item too heavy → 0" },
      { args: [[1, 1, 1], [1, 2, 3], 2], expected: 5, label: "pick best 2 of 3 → 5", hidden: true },
    ],
    solution: `function knapsack(weights, values, capacity) {\n  const n = weights.length;\n  const dp = Array.from({ length: n + 1 }, () => new Array(capacity + 1).fill(0));\n  for (let i = 1; i <= n; i++) {\n    for (let w = 0; w <= capacity; w++) {\n      dp[i][w] = dp[i-1][w]; // don't take item i\n      if (weights[i-1] <= w) {\n        dp[i][w] = Math.max(dp[i][w], dp[i-1][w - weights[i-1]] + values[i-1]);\n      }\n    }\n  }\n  return dp[n][capacity];\n}`,
    solutionExplanation: "Build an (n+1)×(capacity+1) table. dp[i][w] = max value using the first i items with weight limit w. For each item, choose: don't take it (dp[i-1][w]) or take it (dp[i-1][w-weight]+value) if it fits.",
    hints: ["dp[i][w] = best value using items 1..i with capacity w", "Two choices per item: skip it (same as previous row) or take it (if it fits)", "If you take it: dp[i-1][w - weights[i-1]] + values[i-1]"],
    tags: ["DP", "knapsack", "2D-DP"], estimatedMinutes: 25,
  },
];
