import { Exercise, AnyExercise } from "./types";
import { ALL_EXTRA_EXERCISES } from "./moreExercises";
import { ALL_TREE_GRAPH_EXERCISES } from "./treeGraphExercises";
import { DP_EXERCISES } from "./dpExercises";
import { BIT_EXERCISES } from "./bitExercises";
import { TEST_WRITING_EXERCISES, getTestWritingExerciseById } from "./testWritingExercises";
import { AUTH_EXERCISES } from "./authExercises";

// ── Tier 1–2 Foundations (original exercises) ─────────────────────────────
const FOUNDATION_EXERCISES: Exercise[] = [
  {
    id: "sum-array",
    tier: 1, category: "arrays",
    title: "Sum an Array",
    tagline: "Add every number in the list.",
    description: "Write `sumArray(nums)` that returns the sum of all numbers. Use `reduce` — not a `for` loop.",
    why: "Reduce is one of the most powerful array tools. If you can't write it from memory, you're reaching for lodash every time.",
    analogy: "Think of a cash register — you start at $0 and add each item's price as you scan.",
    examples: [
      { input: "sumArray([1, 2, 3, 4, 5])", output: "15" },
      { input: "sumArray([])", output: "0", note: "Empty array returns 0" },
      { input: "sumArray([-1, -2, 3])", output: "0" },
    ],
    starterCode: `function sumArray(nums) {\n  // your code here\n}`,
    functionName: "sumArray",
    testCases: [
      { args: [[1, 2, 3, 4, 5]], expected: 15, label: "[1,2,3,4,5] → 15" },
      { args: [[0]], expected: 0, label: "[0] → 0" },
      { args: [[-1, -2, 3]], expected: 0, label: "[-1,-2,3] → 0" },
      { args: [[]], expected: 0, label: "[] → 0", hidden: true },
      { args: [[100, 200, 300]], expected: 600, label: "large numbers", hidden: true },
    ],
    solution: `function sumArray(nums) {\n  return nums.reduce((acc, n) => acc + n, 0);\n}`,
    solutionExplanation: "reduce takes an accumulator (acc) starting at 0, and adds each element n to it. The second argument to reduce is the initial value.",
    hints: ["reduce takes two arguments: a callback and an initial value", "The callback receives (accumulator, currentValue)"],
    tags: ["reduce", "basics"], estimatedMinutes: 5,
  },
  {
    id: "filter-even",
    tier: 1, category: "arrays",
    title: "Filter Even Numbers",
    tagline: "Keep only the even ones.",
    description: "Write `filterEven(nums)` that returns a new array containing only the even numbers.",
    why: "filter is one of three array methods you'll use daily. Know it cold.",
    analogy: "A bouncer at a club with an even-numbers-only policy.",
    examples: [
      { input: "filterEven([1, 2, 3, 4, 5, 6])", output: "[2, 4, 6]" },
      { input: "filterEven([1, 3, 5])", output: "[]" },
    ],
    starterCode: `function filterEven(nums) {\n  // your code here\n}`,
    functionName: "filterEven",
    testCases: [
      { args: [[1, 2, 3, 4, 5, 6]], expected: [2, 4, 6], label: "mixed → evens" },
      { args: [[1, 3, 5]], expected: [], label: "all odd → empty" },
      { args: [[2, 4, 6]], expected: [2, 4, 6], label: "all even → same" },
      { args: [[0, -2, 7]], expected: [0, -2], label: "zero and negatives", hidden: true },
    ],
    solution: `function filterEven(nums) {\n  return nums.filter(n => n % 2 === 0);\n}`,
    solutionExplanation: "filter creates a new array with elements where the callback returns true. n % 2 === 0 checks if n is divisible by 2 (even).",
    hints: ["Use the filter method", "Even numbers have no remainder when divided by 2"],
    tags: ["filter", "basics"], estimatedMinutes: 5,
  },
  {
    id: "find-max",
    tier: 1, category: "arrays",
    title: "Find the Max",
    tagline: "No Math.max allowed.",
    description: "Write `findMax(nums)` that returns the largest number in the array. You cannot use `Math.max`.",
    why: "Understanding iteration by implementing it from scratch is fundamental. Math.max is a crutch if you've never done it manually.",
    examples: [
      { input: "findMax([3, 1, 4, 1, 5, 9, 2, 6])", output: "9" },
      { input: "findMax([-1, -5, -3])", output: "-1" },
    ],
    starterCode: `function findMax(nums) {\n  // no Math.max\n}`,
    functionName: "findMax",
    testCases: [
      { args: [[3, 1, 4, 1, 5, 9, 2, 6]], expected: 9, label: "typical array" },
      { args: [[-1, -5, -3]], expected: -1, label: "all negatives" },
      { args: [[42]], expected: 42, label: "single element" },
      { args: [[1, 1, 1]], expected: 1, label: "all same", hidden: true },
    ],
    solution: `function findMax(nums) {\n  return nums.reduce((max, n) => n > max ? n : max, nums[0]);\n}`,
    solutionExplanation: "Use reduce to track the running maximum. Start with nums[0] as the initial max, and update whenever you find a larger number.",
    hints: ["You can use reduce for this too", "Keep track of the largest number seen so far"],
    tags: ["reduce", "iteration"], estimatedMinutes: 8,
  },
  {
    id: "remove-duplicates",
    tier: 1, category: "arrays",
    title: "Remove Duplicates",
    tagline: "One of each — that's all.",
    description: "Write `removeDuplicates(arr)` that returns a new array with duplicate values removed. Preserve the original order.",
    why: "You'll do this on every real project. Know at least two ways to do it.",
    analogy: "You're checking into a hotel — each guest only gets one room key even if they ask twice.",
    examples: [
      { input: "removeDuplicates([1, 2, 2, 3, 3, 4])", output: "[1, 2, 3, 4]" },
      { input: "removeDuplicates(['a', 'b', 'a'])", output: "['a', 'b']" },
    ],
    starterCode: `function removeDuplicates(arr) {\n  // your code here\n}`,
    functionName: "removeDuplicates",
    testCases: [
      { args: [[1, 2, 2, 3, 3, 4]], expected: [1, 2, 3, 4], label: "basic dedup" },
      { args: [["a", "b", "a"]], expected: ["a", "b"], label: "strings" },
      { args: [[1, 1, 1, 1]], expected: [1], label: "all same" },
      { args: [[]], expected: [], label: "empty", hidden: true },
      { args: [[1, 2, 3]], expected: [1, 2, 3], label: "no duplicates", hidden: true },
    ],
    solution: `function removeDuplicates(arr) {\n  return [...new Set(arr)];\n}`,
    solutionExplanation: "Set is a built-in that only stores unique values. Spreading it back into an array gives you unique items in insertion order.",
    hints: ["JavaScript has a built-in data structure that only stores unique values", "Try: new Set(arr)"],
    tags: ["Set", "dedup"], estimatedMinutes: 5,
  },
  {
    id: "reverse-string",
    tier: 1, category: "strings",
    title: "Reverse a String",
    tagline: "No .reverse() on the string.",
    description: "Write `reverseString(str)` that returns the string reversed. You may split into an array first.",
    why: "Classic. Forces you to know how strings and arrays interact.",
    examples: [
      { input: "reverseString('hello')", output: "'olleh'" },
      { input: "reverseString('ab')", output: "'ba'" },
    ],
    starterCode: `function reverseString(str) {\n  // your code here\n}`,
    functionName: "reverseString",
    testCases: [
      { args: ["hello"], expected: "olleh", label: "'hello' → 'olleh'" },
      { args: ["ab"], expected: "ba", label: "'ab' → 'ba'" },
      { args: ["a"], expected: "a", label: "single char" },
      { args: [""], expected: "", label: "empty string", hidden: true },
      { args: ["racecar"], expected: "racecar", label: "palindrome", hidden: true },
    ],
    solution: `function reverseString(str) {\n  return str.split('').reverse().join('');\n}`,
    solutionExplanation: "split('') converts the string to an array of characters, reverse() reverses the array in place, join('') reassembles it into a string.",
    hints: ["Strings have a split method", "Arrays have a reverse method"],
    tags: ["strings", "split-reverse-join"], estimatedMinutes: 5,
  },
  {
    id: "is-palindrome",
    tier: 1, category: "strings",
    title: "Is It a Palindrome?",
    tagline: "Same forwards and backwards.",
    description: "Write `isPalindrome(str)` that returns `true` if the string reads the same forwards and backwards. Ignore case.",
    why: "This tests if you can compose simple string operations into a clean solution.",
    analogy: "'racecar' reads the same from both ends — like a mirror.",
    examples: [
      { input: "isPalindrome('racecar')", output: "true" },
      { input: "isPalindrome('RaceCar')", output: "true", note: "case insensitive" },
      { input: "isPalindrome('hello')", output: "false" },
    ],
    starterCode: `function isPalindrome(str) {\n  // your code here\n}`,
    functionName: "isPalindrome",
    testCases: [
      { args: ["racecar"], expected: true, label: "'racecar' is palindrome" },
      { args: ["RaceCar"], expected: true, label: "case insensitive" },
      { args: ["hello"], expected: false, label: "'hello' is not" },
      { args: ["a"], expected: true, label: "single char", hidden: true },
      { args: ["Madam"], expected: true, label: "'Madam'", hidden: true },
    ],
    solution: `function isPalindrome(str) {\n  const s = str.toLowerCase();\n  return s === s.split('').reverse().join('');\n}`,
    solutionExplanation: "Lowercase both ends of the comparison, then check if the string equals its reverse.",
    hints: ["toLowerCase() first", "Compare the string to its own reverse"],
    tags: ["strings", "palindrome"], estimatedMinutes: 8,
  },
  {
    id: "title-case",
    tier: 1, category: "strings",
    title: "Title Case",
    tagline: "First letter of each word capitalized.",
    description: "Write `titleCase(str)` that returns the string with the first letter of each word capitalized and the rest lowercased.",
    why: "String manipulation is constant in UI work. This tests your ability to map over parts of a string.",
    examples: [
      { input: "titleCase('hello world')", output: "'Hello World'" },
      { input: "titleCase('the quick BROWN fox')", output: "'The Quick Brown Fox'" },
    ],
    starterCode: `function titleCase(str) {\n  // your code here\n}`,
    functionName: "titleCase",
    testCases: [
      { args: ["hello world"], expected: "Hello World", label: "basic" },
      { args: ["the quick BROWN fox"], expected: "The Quick Brown Fox", label: "mixed case input" },
      { args: ["a"], expected: "A", label: "single word" },
      { args: ["one two three four"], expected: "One Two Three Four", label: "four words", hidden: true },
    ],
    solution: `function titleCase(str) {\n  return str.toLowerCase().split(' ')\n    .map(word => word.charAt(0).toUpperCase() + word.slice(1))\n    .join(' ');\n}`,
    solutionExplanation: "Lowercase everything first, split by spaces, map each word to capitalize its first letter, then rejoin.",
    hints: ["Split the string into words first", "For each word: charAt(0).toUpperCase() + word.slice(1)"],
    tags: ["strings", "map"], estimatedMinutes: 8,
  },
  {
    id: "count-occurrences",
    tier: 2, category: "arrays",
    title: "Count Occurrences",
    tagline: "Build a frequency map of every element.",
    description: "Write `countOccurrences(arr)` that returns an object where keys are the elements and values are how many times each appears.",
    why: "Frequency maps are everywhere — analytics dashboards, vote tallying, word counters. This pattern alone unlocks dozens of real problems.",
    analogy: "It's like taking attendance: mark each person as they arrive.",
    examples: [
      { input: "countOccurrences(['a', 'b', 'a', 'c', 'b', 'a'])", output: "{ a: 3, b: 2, c: 1 }" },
      { input: "countOccurrences([1, 1, 2, 3])", output: "{ 1: 2, 2: 1, 3: 1 }" },
    ],
    starterCode: `function countOccurrences(arr) {\n  // your code here\n}`,
    functionName: "countOccurrences",
    testCases: [
      { args: [["a", "b", "a", "c", "b", "a"]], expected: { a: 3, b: 2, c: 1 }, label: "strings" },
      { args: [[1, 1, 2, 3]], expected: { 1: 2, 2: 1, 3: 1 }, label: "numbers" },
      { args: [["x"]], expected: { x: 1 }, label: "single element" },
      { args: [[]], expected: {}, label: "empty array", hidden: true },
    ],
    solution: `function countOccurrences(arr) {\n  return arr.reduce((acc, el) => {\n    acc[el] = (acc[el] ?? 0) + 1;\n    return acc;\n  }, {});\n}`,
    solutionExplanation: "Use reduce to build an object. For each element, increment its count (defaulting to 0 if not seen yet).",
    hints: ["reduce with an object as the accumulator", "acc[el] = (acc[el] || 0) + 1"],
    tags: ["reduce", "frequency-map", "objects"], estimatedMinutes: 10,
  },
  {
    id: "group-by",
    tier: 2, category: "objects",
    title: "Group By",
    tagline: "Sort objects into buckets by a key.",
    description: "Write `groupBy(arr, key)` that groups an array of objects by the value of the given property key.",
    why: "You will write this pattern every week on a real project. It appears in dashboards, reports, data processing — everywhere.",
    analogy: "Think of sorting mail by ZIP code. Each pile is a group.",
    examples: [
      { input: "groupBy([{type:'a'},{type:'b'},{type:'a'}], 'type')", output: "{ a: [{type:'a'},{type:'a'}], b: [{type:'b'}] }" },
    ],
    starterCode: `function groupBy(arr, key) {\n  // your code here\n}`,
    functionName: "groupBy",
    testCases: [
      {
        args: [[{ type: "a" }, { type: "b" }, { type: "a" }], "type"],
        expected: { a: [{ type: "a" }, { type: "a" }], b: [{ type: "b" }] },
        label: "group by 'type'",
      },
      {
        args: [[{ age: 20, name: "Ali" }, { age: 30, name: "Bob" }, { age: 20, name: "Cam" }], "age"],
        expected: { 20: [{ age: 20, name: "Ali" }, { age: 20, name: "Cam" }], 30: [{ age: 30, name: "Bob" }] },
        label: "group by 'age'",
      },
      { args: [[], "key"], expected: {}, label: "empty array", hidden: true },
    ],
    solution: `function groupBy(arr, key) {\n  return arr.reduce((groups, item) => {\n    const val = item[key];\n    if (!groups[val]) groups[val] = [];\n    groups[val].push(item);\n    return groups;\n  }, {});\n}`,
    solutionExplanation: "reduce builds the groups object. For each item, get the value of the key, create a new bucket array if needed, then push the item in.",
    hints: ["reduce with an object accumulator", "Initialize the group to [] if it doesn't exist yet"],
    tags: ["reduce", "groupBy", "objects"], estimatedMinutes: 12,
  },
  {
    id: "flatten-array",
    tier: 2, category: "arrays",
    title: "Flatten an Array",
    tagline: "Collapse nested arrays into one flat list.",
    description: "Write `flattenArray(arr)` that flattens a deeply nested array into a single-level array. Do not use `Array.prototype.flat`.",
    why: "Nested data is everywhere — file systems, component trees, JSON responses. Knowing how to flatten it is a fundamental tool.",
    examples: [
      { input: "flattenArray([1, [2, [3, [4]]]])", output: "[1, 2, 3, 4]" },
    ],
    starterCode: `function flattenArray(arr) {\n  // no Array.flat allowed\n}`,
    functionName: "flattenArray",
    testCases: [
      { args: [[1, [2, [3, [4]]]]], expected: [1, 2, 3, 4], label: "deeply nested" },
      { args: [[1, 2, 3]], expected: [1, 2, 3], label: "already flat" },
      { args: [[[1, 2], [3, 4]]], expected: [1, 2, 3, 4], label: "one level nested" },
      { args: [[]], expected: [], label: "empty", hidden: true },
    ],
    solution: `function flattenArray(arr) {\n  return arr.reduce((flat, item) => {\n    return flat.concat(Array.isArray(item) ? flattenArray(item) : item);\n  }, []);\n}`,
    solutionExplanation: "Use reduce with recursion. If an item is an array, recursively flatten it. If it's not, just concat it.",
    hints: ["Think recursively — if an element is an array, flatten that too", "Array.isArray() tells you if something is an array"],
    tags: ["recursion", "reduce", "flatten"], estimatedMinutes: 12,
  },
  {
    id: "memoize",
    tier: 2, category: "functions",
    title: "Memoize",
    tagline: "Cache the result. Never compute twice.",
    description: "Write `memoize(fn)` that returns a new version of any function that caches its results. If called with the same arguments again, return the cached result.",
    why: "Memoization is how you turn an O(2^n) recursive solution into O(n). It's also how React.memo and useMemo work under the hood.",
    analogy: "A student who writes the answer on a note card the first time, then just reads the card next time.",
    examples: [
      { input: "const memo = memoize(n => n * 2);\nmemo(5) // calls fn\nmemo(5) // uses cache", output: "10 (both times)" },
    ],
    starterCode: `function memoize(fn) {\n  // return a new function that caches fn's results\n}`,
    functionName: "memoize",
    testCases: [{ args: [(x: number) => x * 2], expected: 10, label: "caches doubles" }],
    solution: `function memoize(fn) {\n  const cache = new Map();\n  return function(...args) {\n    const key = JSON.stringify(args);\n    if (cache.has(key)) return cache.get(key);\n    const result = fn.apply(this, args);\n    cache.set(key, result);\n    return result;\n  };\n}`,
    solutionExplanation: "Store a Map as a closure. On each call, JSON.stringify the args to make a cache key. Return from cache if found, otherwise compute and store.",
    hints: ["Use a closure to hold the cache", "JSON.stringify(args) makes a reliable cache key for simple arguments"],
    tags: ["closures", "cache", "higher-order"], estimatedMinutes: 15,
  },
  {
    id: "chunk-array",
    tier: 2, category: "arrays",
    title: "Chunk an Array",
    tagline: "Split into pieces of size n.",
    description: "Write `chunkArray(arr, size)` that splits an array into chunks of the given size. The last chunk may be smaller.",
    why: "Pagination, batch processing, grid layouts — chunking is a real operation you'll reach for constantly.",
    examples: [
      { input: "chunkArray([1,2,3,4,5], 2)", output: "[[1,2],[3,4],[5]]" },
    ],
    starterCode: `function chunkArray(arr, size) {\n  // your code here\n}`,
    functionName: "chunkArray",
    testCases: [
      { args: [[1, 2, 3, 4, 5], 2], expected: [[1, 2], [3, 4], [5]], label: "basic chunk" },
      { args: [[1, 2, 3], 3], expected: [[1, 2, 3]], label: "exact fit" },
      { args: [[1], 5], expected: [[1]], label: "smaller than chunk size" },
      { args: [[], 2], expected: [], label: "empty array", hidden: true },
    ],
    solution: `function chunkArray(arr, size) {\n  const chunks = [];\n  for (let i = 0; i < arr.length; i += size) {\n    chunks.push(arr.slice(i, i + size));\n  }\n  return chunks;\n}`,
    solutionExplanation: "Loop through the array by jumping `size` elements at a time, slicing out each chunk and pushing to the result.",
    hints: ["slice(i, i + size) extracts a portion of the array", "Increment i by size each iteration"],
    tags: ["arrays", "slice", "pagination"], estimatedMinutes: 10,
  },
  {
    id: "deep-equal",
    tier: 3, category: "objects",
    title: "Deep Equal",
    tagline: "Are these two objects actually the same?",
    description: "Write `deepEqual(a, b)` that returns `true` if both values are deeply equal — including nested objects and arrays.",
    why: "Testing, state comparison, React bailouts — deep equality is a tool that every serious developer needs to be able to build.",
    examples: [
      { input: "deepEqual({a:1,b:{c:2}}, {a:1,b:{c:2}})", output: "true" },
      { input: "deepEqual([1,[2,3]], [1,[2,3]])", output: "true" },
    ],
    starterCode: `function deepEqual(a, b) {\n  // your code here\n}`,
    functionName: "deepEqual",
    testCases: [
      { args: [{ a: 1, b: { c: 2 } }, { a: 1, b: { c: 2 } }], expected: true, label: "nested objects equal" },
      { args: [{ a: 1 }, { a: 2 }], expected: false, label: "different values" },
      { args: [[1, [2, 3]], [1, [2, 3]]], expected: true, label: "nested arrays equal" },
      { args: [null, null], expected: true, label: "both null", hidden: true },
      { args: [{ a: 1 }, { a: 1, b: 2 }], expected: false, label: "different key count", hidden: true },
    ],
    solution: `function deepEqual(a, b) {\n  if (a === b) return true;\n  if (a === null || b === null) return false;\n  if (typeof a !== 'object' || typeof b !== 'object') return false;\n  const keysA = Object.keys(a), keysB = Object.keys(b);\n  if (keysA.length !== keysB.length) return false;\n  return keysA.every(key => deepEqual(a[key], b[key]));\n}`,
    solutionExplanation: "Handle primitives with ===, return false for null/type mismatches, check key counts match, then recursively compare each key's value.",
    hints: ["Handle the base cases first: primitives use ===", "For objects, check that they have the same number of keys, then recurse"],
    tags: ["recursion", "objects", "equality"], estimatedMinutes: 15,
  },
  {
    id: "pipe",
    tier: 3, category: "functions",
    title: "Pipe Functions",
    tagline: "Chain functions left to right.",
    description: "Write `pipe(...fns)` that returns a function. When called with a value, it passes that value through each function in order, left to right.",
    why: "Functional composition is how you build complex transformations from simple parts without nesting 10 function calls.",
    analogy: "Like an assembly line — each station does one thing and passes the result to the next.",
    examples: [
      { input: "const transform = pipe(x => x + 1, x => x * 2);\ntransform(3)", output: "8", note: "(3+1)*2 = 8" },
    ],
    starterCode: `function pipe(...fns) {\n  // return a function that runs value through each fn in order\n}`,
    functionName: "pipe",
    testCases: [{ args: [(x: number) => x + 1, (x: number) => x * 2], expected: 8, label: "add then multiply" }],
    solution: `function pipe(...fns) {\n  return function(value) {\n    return fns.reduce((acc, fn) => fn(acc), value);\n  };\n}`,
    solutionExplanation: "Collect all functions with rest params, return a new function that uses reduce to thread the value through each function in sequence.",
    hints: ["Use rest params: ...fns", "reduce over the functions, passing the accumulated result to each next fn"],
    tags: ["functional", "reduce", "composition"], estimatedMinutes: 12,
  },
  {
    id: "deep-clone",
    tier: 3, category: "objects",
    title: "Deep Clone",
    tagline: "Copy everything — no shared references.",
    description: "Write `deepClone(obj)` that creates a full deep copy of an object or array. Changes to the clone must not affect the original. No `JSON.stringify`.",
    why: "Shared object references cause the most subtle, hard-to-debug bugs in JavaScript. Understanding how to clone properly is essential.",
    examples: [
      { input: "const clone = deepClone({a: {b: 1}});\nclone.a.b = 99;", output: "original.a.b is still 1" },
    ],
    starterCode: `function deepClone(obj) {\n  // no JSON.stringify/parse\n}`,
    functionName: "deepClone",
    testCases: [
      { args: [{ a: { b: 1 }, c: [1, 2, 3] }], expected: { a: { b: 1 }, c: [1, 2, 3] }, label: "clones nested object" },
      { args: [[1, [2, [3]]]], expected: [1, [2, [3]]], label: "clones nested array" },
      { args: [42], expected: 42, label: "primitive passthrough", hidden: true },
      { args: [null], expected: null, label: "null passthrough", hidden: true },
    ],
    solution: `function deepClone(obj) {\n  if (obj === null || typeof obj !== 'object') return obj;\n  if (Array.isArray(obj)) return obj.map(deepClone);\n  return Object.fromEntries(\n    Object.entries(obj).map(([k, v]) => [k, deepClone(v)])\n  );\n}`,
    solutionExplanation: "Base case: return primitives as-is. For arrays: map each element recursively. For objects: clone each value recursively using Object.entries.",
    hints: ["Check for primitives first — they don't need cloning", "Arrays and objects are handled differently"],
    tags: ["recursion", "objects", "cloning"], estimatedMinutes: 15,
  },
  {
    id: "template-engine",
    tier: 3, category: "strings",
    title: "Template Engine",
    tagline: "Replace {{variables}} in a string.",
    description: "Write `template(str, data)` that replaces all `{{key}}` placeholders in the string with the corresponding value from the `data` object.",
    why: "Email templates, notification messages, dynamic SQL — this pattern is everywhere.",
    examples: [
      { input: "template('Hello {{name}}!', {name: 'World'})", output: "'Hello World!'" },
    ],
    starterCode: `function template(str, data) {\n  // your code here\n}`,
    functionName: "template",
    testCases: [
      { args: ["Hello {{name}}!", { name: "World" }], expected: "Hello World!", label: "basic substitution" },
      { args: ["{{a}} + {{b}} = {{c}}", { a: 1, b: 2, c: 3 }], expected: "1 + 2 = 3", label: "multiple values" },
      { args: ["No vars here", {}], expected: "No vars here", label: "no placeholders" },
      { args: ["{{x}} and {{x}}", { x: "hi" }], expected: "hi and hi", label: "repeated var", hidden: true },
    ],
    solution: `function template(str, data) {\n  return str.replace(/\\{\\{(\\w+)\\}\\}/g, (_, key) => data[key] ?? '');\n}`,
    solutionExplanation: "Use String.replace with a regex that matches {{word}}. The callback receives the full match and capture group (key), and returns the data value.",
    hints: ["String.replace can take a function as the second argument", "The regex pattern is /\\{\\{(\\w+)\\}\\}/g"],
    tags: ["regex", "strings", "templates"], estimatedMinutes: 12,
  },
  {
    id: "binary-search",
    tier: 4, category: "algorithms",
    title: "Binary Search",
    tagline: "Find the target in O(log n) time.",
    description: "Write `binarySearch(arr, target)` that searches a sorted array and returns the index of the target. Return -1 if not found. No `indexOf`.",
    why: "Binary search is the difference between searching 1 million records in 1 second vs 1ms.",
    analogy: "Open a dictionary to the middle — if your word comes before that page, search left. Otherwise right.",
    examples: [
      { input: "binarySearch([1,3,5,7,9,11], 7)", output: "3" },
      { input: "binarySearch([1,3,5], 4)", output: "-1" },
    ],
    starterCode: `function binarySearch(arr, target) {\n  // no indexOf\n}`,
    functionName: "binarySearch",
    testCases: [
      { args: [[1, 3, 5, 7, 9, 11], 7], expected: 3, label: "found in middle" },
      { args: [[1, 3, 5], 4], expected: -1, label: "not found" },
      { args: [[5], 5], expected: 0, label: "single element found" },
      { args: [[1, 2, 3, 4, 5], 1], expected: 0, label: "first element", hidden: true },
      { args: [[1, 2, 3, 4, 5], 5], expected: 4, label: "last element", hidden: true },
    ],
    solution: `function binarySearch(arr, target) {\n  let lo = 0, hi = arr.length - 1;\n  while (lo <= hi) {\n    const mid = Math.floor((lo + hi) / 2);\n    if (arr[mid] === target) return mid;\n    if (arr[mid] < target) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}`,
    solutionExplanation: "Maintain lo and hi pointers. At each step, check the midpoint. If target is larger, search right half. If smaller, search left half.",
    hints: ["Keep a left and right pointer", "mid = Math.floor((lo + hi) / 2)", "If arr[mid] < target, search right: lo = mid + 1"],
    tags: ["binary-search", "O(log n)", "algorithms"], estimatedMinutes: 20,
  },
  {
    id: "two-sum",
    tier: 4, category: "algorithms",
    title: "Two Sum",
    tagline: "Find the pair that adds to target.",
    description: "Write `twoSum(nums, target)` that returns the indices of two numbers that add up to `target`. Solve in O(n) time.",
    why: "The most common interview question for a reason — it teaches you when to trade memory for time using a hash map.",
    analogy: "Looking for a $100 bill. You check each bill and ask 'Is the complement already in my pocket?'",
    examples: [
      { input: "twoSum([2, 7, 11, 15], 9)", output: "[0, 1]", note: "2+7=9" },
    ],
    starterCode: `function twoSum(nums, target) {\n  // O(n) solution — use a Map\n}`,
    functionName: "twoSum",
    testCases: [
      { args: [[2, 7, 11, 15], 9], expected: [0, 1], label: "basic" },
      { args: [[3, 2, 4], 6], expected: [1, 2], label: "non-adjacent" },
      { args: [[3, 3], 6], expected: [0, 1], label: "same value", hidden: true },
    ],
    solution: `function twoSum(nums, target) {\n  const seen = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const complement = target - nums[i];\n    if (seen.has(complement)) return [seen.get(complement), i];\n    seen.set(nums[i], i);\n  }\n}`,
    solutionExplanation: "Use a Map to track numbers seen so far. For each number, check if its complement (target - num) is in the Map. If yes, return both indices.",
    hints: ["For each number n, you need to find (target - n)", "A Map lets you look up in O(1). Store num → index"],
    tags: ["hash-map", "O(n)", "two-pointers"], estimatedMinutes: 20,
  },
  {
    id: "merge-sort",
    tier: 4, category: "algorithms",
    title: "Merge Sort",
    tagline: "Sort in O(n log n) with divide and conquer.",
    description: "Write `mergeSort(arr)` that sorts an array using the merge sort algorithm. Do not use the built-in sort.",
    why: "Merge sort teaches divide-and-conquer — the most powerful algorithm design pattern.",
    analogy: "Split your deck of cards in half, sort each half, then merge the two sorted halves together.",
    examples: [
      { input: "mergeSort([3, 1, 4, 1, 5, 9, 2, 6])", output: "[1, 1, 2, 3, 4, 5, 6, 9]" },
    ],
    starterCode: `function mergeSort(arr) {\n  // divide and conquer — no Array.sort\n}`,
    functionName: "mergeSort",
    testCases: [
      { args: [[3, 1, 4, 1, 5, 9, 2, 6]], expected: [1, 1, 2, 3, 4, 5, 6, 9], label: "basic sort" },
      { args: [[5, 4, 3, 2, 1]], expected: [1, 2, 3, 4, 5], label: "reverse order" },
      { args: [[1]], expected: [1], label: "single element" },
      { args: [[2, 1]], expected: [1, 2], label: "two elements", hidden: true },
    ],
    solution: `function mergeSort(arr) {\n  if (arr.length <= 1) return arr;\n  const mid = Math.floor(arr.length / 2);\n  const left = mergeSort(arr.slice(0, mid));\n  const right = mergeSort(arr.slice(mid));\n  return merge(left, right);\n}\nfunction merge(left, right) {\n  const result = [];\n  let i = 0, j = 0;\n  while (i < left.length && j < right.length) {\n    if (left[i] <= right[j]) result.push(left[i++]);\n    else result.push(right[j++]);\n  }\n  return result.concat(left.slice(i), right.slice(j));\n}`,
    solutionExplanation: "Split the array in half, recursively sort each half, then merge the two sorted halves by picking the smallest element from each in order.",
    hints: ["Base case: array of 0 or 1 elements is already sorted", "The merge step compares elements from two sorted arrays"],
    tags: ["recursion", "divide-and-conquer", "O(n log n)"], estimatedMinutes: 25,
  },
];

// ── Quick Sort ───────────────────────────────────────────────────────────────
const QUICK_SORT_EXERCISE: Exercise = {
  id: "quick-sort",
  tier: 4, category: "algorithms",
  title: "Quick Sort",
  tagline: "Partition, recurse, conquer.",
  description: "Write `quickSort(arr)` that returns a new sorted array using the quicksort algorithm. Choose a pivot, partition the array into elements less than, equal to, and greater than the pivot, then recursively sort each partition.",
  why: "Quick Sort is the most widely used sorting algorithm in practice — it's the default in most language runtimes. Understanding it alongside Merge Sort shows two completely different divide-and-conquer strategies: one splits evenly (merge), one splits by value (quick).",
  analogy: "Choose a dividing wall (the pivot). Put everyone shorter on the left, taller on the right. Now sort each side the same way — the whole line ends up sorted.",
  examples: [
    { input: "quickSort([3,6,8,10,1,2,1])", output: "[1,1,2,3,6,8,10]" },
    { input: "quickSort([5,4,3,2,1])", output: "[1,2,3,4,5]" },
    { input: "quickSort([])", output: "[]" },
  ],
  starterCode: `function quickSort(arr) {\n  // pick a pivot, partition, recurse on each side\n}`,
  functionName: "quickSort",
  testCases: [
    { args: [[3, 6, 8, 10, 1, 2, 1]], expected: [1, 1, 2, 3, 6, 8, 10], label: "basic unsorted array" },
    { args: [[5, 4, 3, 2, 1]], expected: [1, 2, 3, 4, 5], label: "reverse sorted" },
    { args: [[]], expected: [], label: "empty array" },
    { args: [[1]], expected: [1], label: "single element" },
    { args: [[2, 2, 2]], expected: [2, 2, 2], label: "all duplicates", hidden: true },
    { args: [[1, 2, 3, 4, 5]], expected: [1, 2, 3, 4, 5], label: "already sorted", hidden: true },
  ],
  solution: `function quickSort(arr) {\n  if (arr.length <= 1) return arr;\n  const pivot = arr[Math.floor(arr.length / 2)];\n  const left   = arr.filter(x => x < pivot);\n  const middle = arr.filter(x => x === pivot);\n  const right  = arr.filter(x => x > pivot);\n  return [...quickSort(left), ...middle, ...quickSort(right)];\n}`,
  solutionExplanation: "Pick the middle element as the pivot. Filter into three buckets: less than, equal to, and greater than the pivot. Recursively sort left and right buckets, then concatenate. The 'equal' bucket handles duplicates cleanly.",
  hints: [
    "Base case: array of 0 or 1 elements is already sorted",
    "Partition into three arrays: less, equal, greater than pivot",
    "Recursively sort the less and greater partitions, then spread them together",
  ],
  tags: ["sorting", "recursion", "divide-and-conquer", "O(n log n)"],
  estimatedMinutes: 20,
};

// ── Merged complete exercise list ────────────────────────────────────────────
export const EXERCISES: Exercise[] = [
  ...FOUNDATION_EXERCISES,
  ...ALL_EXTRA_EXERCISES,
  QUICK_SORT_EXERCISE,
  ...ALL_TREE_GRAPH_EXERCISES,
  ...DP_EXERCISES,
  ...BIT_EXERCISES,
  ...AUTH_EXERCISES,
];

export const ALL_GYM_EXERCISES: AnyExercise[] = [
  ...EXERCISES,
  ...TEST_WRITING_EXERCISES,
];

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find(e => e.id === id);
}

export function getExercisesByTier(tier: number): Exercise[] {
  return EXERCISES.filter(e => e.tier === tier);
}

export function getAnyExerciseById(id: string): AnyExercise | undefined {
  return (
    EXERCISES.find(e => e.id === id) ??
    getTestWritingExerciseById(id)
  );
}
