import { Exercise } from "./types";

// ── Data Structures ───────────────────────────────────────────────────────────
export const DATA_STRUCTURE_EXERCISES: Exercise[] = [
  {
    id: "implement-stack",
    format: "solve",
    tier: 2, category: "data-structures",
    title: "Implement a Stack",
    tagline: "Last in, first out.",
    description: "Create a `Stack` class with: `push(val)`, `pop()` (returns and removes top), `peek()` (returns top without removing), `isEmpty()`, and `size()`. Return `null` from pop/peek if empty.",
    why: "Stacks power undo/redo, browser history, call stacks, expression evaluation, and DFS traversal. Understanding them from scratch makes every framework clearer.",
    analogy: "A stack of plates — you can only add or remove from the top.",
    examples: [
      { input: "const s = new Stack();\ns.push(1); s.push(2);\ns.peek()", output: "2" },
      { input: "s.pop()", output: "2 (and removes it)" },
      { input: "s.isEmpty()", output: "false" },
    ],
    starterCode: `class Stack {\n  constructor() {\n    // your code here\n  }\n\n  push(val) {\n    // add to top\n  }\n\n  pop() {\n    // remove and return top\n  }\n\n  peek() {\n    // return top without removing\n  }\n\n  isEmpty() {\n    // return true if empty\n  }\n\n  size() {\n    // return number of items\n  }\n}`,
    functionName: "Stack",
    testCases: [
      { args: [], expected: true, label: "Stack class is defined" },
    ],
    solution: `class Stack {\n  constructor() {\n    this.items = [];\n  }\n  push(val) { this.items.push(val); }\n  pop() { return this.items.length ? this.items.pop() : null; }\n  peek() { return this.items.length ? this.items[this.items.length - 1] : null; }\n  isEmpty() { return this.items.length === 0; }\n  size() { return this.items.length; }\n}`,
    solutionExplanation: "Use an internal array. push/pop map directly to Array methods. peek reads the last index without removing. isEmpty checks length.",
    hints: ["An array with push and pop is already a stack — wrap it", "peek: return items[items.length - 1]"],
    tags: ["stack", "data-structures", "OOP"], estimatedMinutes: 12,
  },
  {
    id: "implement-queue",
    format: "solve",
    tier: 2, category: "data-structures",
    title: "Implement a Queue",
    tagline: "First in, first out.",
    description: "Create a `Queue` class with: `enqueue(val)`, `dequeue()` (removes from front), `peek()`, `isEmpty()`, and `size()`.",
    why: "Queues power BFS traversal, job queues, print spoolers, message brokers. Every task scheduler in every language uses this concept.",
    analogy: "A line at the grocery store — first person in line is first to be served.",
    examples: [
      { input: "const q = new Queue();\nq.enqueue(1); q.enqueue(2);\nq.dequeue()", output: "1 (removes the first added)" },
      { input: "q.peek()", output: "2" },
    ],
    starterCode: `class Queue {\n  constructor() {\n    // your code here\n  }\n\n  enqueue(val) {\n    // add to back\n  }\n\n  dequeue() {\n    // remove and return front\n  }\n\n  peek() {\n    // return front without removing\n  }\n\n  isEmpty() {}\n\n  size() {}\n}`,
    functionName: "Queue",
    testCases: [
      { args: [], expected: true, label: "Queue class is defined" },
    ],
    solution: `class Queue {\n  constructor() { this.items = []; }\n  enqueue(val) { this.items.push(val); }\n  dequeue() { return this.items.length ? this.items.shift() : null; }\n  peek() { return this.items[0] ?? null; }\n  isEmpty() { return this.items.length === 0; }\n  size() { return this.items.length; }\n}`,
    solutionExplanation: "Use an array where we push to the back (enqueue) and shift from the front (dequeue). Note: shift() is O(n) — a real queue uses a linked list or circular buffer for O(1), but array works fine for learning.",
    hints: ["Enqueue = push to end", "Dequeue = remove from front — which Array method does that?"],
    tags: ["queue", "data-structures", "OOP"], estimatedMinutes: 12,
  },
  {
    id: "valid-parentheses",
    format: "solve",
    tier: 2, category: "data-structures",
    title: "Valid Parentheses",
    tagline: "Every opener has a matching closer.",
    description: "Write `isValid(s)` that returns `true` if the string's brackets are balanced. Valid pairs: `()`, `[]`, `{}`. Every opening bracket must be closed in the correct order.",
    why: "This exact algorithm runs in every code editor, linter, and compiler. Understanding it means you understand how parsers work.",
    analogy: "Russian nesting dolls — the last one you opened must be the first one you close.",
    examples: [
      { input: "isValid('()')", output: "true" },
      { input: "isValid('()[]{}')", output: "true" },
      { input: "isValid('(]')", output: "false" },
      { input: "isValid('([)]')", output: "false", note: "wrong order" },
    ],
    starterCode: `function isValid(s) {\n  // use a stack\n}`,
    functionName: "isValid",
    testCases: [
      { args: ["()"], expected: true, label: "'()' → true" },
      { args: ["()[]{}"], expected: true, label: "'()[]{}' → true" },
      { args: ["(]"], expected: false, label: "'(]' → false" },
      { args: ["([)]"], expected: false, label: "'([)]' → false (wrong order)" },
      { args: ["{[]}"], expected: true, label: "'{[]}' → true" },
      { args: [""], expected: true, label: "empty string → true", hidden: true },
      { args: [")"], expected: false, label: "lone closer → false", hidden: true },
    ],
    solution: `function isValid(s) {\n  const stack = [];\n  const pairs = { ')': '(', ']': '[', '}': '{' };\n  for (const ch of s) {\n    if ('([{'.includes(ch)) stack.push(ch);\n    else if (stack.pop() !== pairs[ch]) return false;\n  }\n  return stack.length === 0;\n}`,
    solutionExplanation: "Push openers onto a stack. When we see a closer, pop the stack and check it matches. If not, invalid. At the end, the stack must be empty.",
    hints: ["Push opening brackets onto a stack", "When you see a closing bracket, check if the top of the stack is its matching opener"],
    tags: ["stack", "parsing"], estimatedMinutes: 15,
  },
  {
    id: "reverse-linked-list",
    format: "solve",
    tier: 3, category: "data-structures",
    title: "Reverse a Linked List",
    tagline: "Flip the direction of every pointer.",
    description: "Given the head of a linked list (nodes have `.val` and `.next`), reverse it in-place and return the new head. A `ListNode` class is provided.",
    why: "The single most common linked list interview question. More importantly, it forces you to think about pointer manipulation — the foundation of memory management.",
    analogy: "A chain of people each holding the shoulder of the person in front. Make each person turn around and hold the person behind them instead.",
    examples: [
      { input: "reverseList(1→2→3→4→5)", output: "5→4→3→2→1" },
      { input: "reverseList(1→2)", output: "2→1" },
    ],
    starterCode: `class ListNode {\n  constructor(val, next = null) {\n    this.val = val;\n    this.next = next;\n  }\n}\n\nfunction reverseList(head) {\n  // reverse in place, return new head\n}`,
    functionName: "reverseList",
    testCases: [
      {
        args: [{ val: 1, next: { val: 2, next: { val: 3, next: null } } }],
        expected: { val: 3, next: { val: 2, next: { val: 1, next: null } } },
        label: "1→2→3 becomes 3→2→1",
      },
      {
        args: [{ val: 1, next: null }],
        expected: { val: 1, next: null },
        label: "single node stays the same",
      },
      { args: [null], expected: null, label: "null → null", hidden: true },
    ],
    solution: `class ListNode {\n  constructor(val, next = null) { this.val = val; this.next = next; }\n}\n\nfunction reverseList(head) {\n  let prev = null, curr = head;\n  while (curr) {\n    const next = curr.next;\n    curr.next = prev;\n    prev = curr;\n    curr = next;\n  }\n  return prev;\n}`,
    solutionExplanation: "Keep three pointers: prev (starts null), curr, next. Each iteration: save curr.next, point curr.next backwards to prev, advance both pointers. When curr is null, prev is the new head.",
    hints: ["You need three variables: prev, curr, and a temp to hold curr.next", "prev starts as null — that becomes the new tail's .next"],
    tags: ["linked-list", "pointers"], estimatedMinutes: 20,
  },
  {
    id: "lru-cache",
    format: "solve",
    tier: 4, category: "data-structures",
    title: "LRU Cache",
    tagline: "O(1) get and put with a size limit.",
    description: "Implement an `LRUCache` class. `get(key)` returns the value or -1. `put(key, val)` inserts or updates. When capacity is exceeded, evict the least recently used item. Both operations must be O(1).",
    why: "LRU cache is in every major system — browsers, databases, CDNs, operating systems. The implementation uses a hash map + doubly linked list, which teaches you how real caches are built.",
    analogy: "A whiteboard with N slots. When it fills up, erase whatever was written on it the longest ago.",
    examples: [
      { input: "const cache = new LRUCache(2);\ncache.put(1, 1); cache.put(2, 2);\ncache.get(1)", output: "1" },
      { input: "cache.put(3, 3); // evicts key 2\ncache.get(2)", output: "-1" },
    ],
    starterCode: `class LRUCache {\n  constructor(capacity) {\n    this.capacity = capacity;\n    // initialize your data structures\n  }\n\n  get(key) {\n    // return value or -1\n  }\n\n  put(key, val) {\n    // insert or update, evict LRU if at capacity\n  }\n}`,
    functionName: "LRUCache",
    testCases: [
      { args: [], expected: true, label: "LRUCache is defined" },
    ],
    solution: `class LRUCache {\n  constructor(capacity) {\n    this.capacity = capacity;\n    this.cache = new Map();\n  }\n  get(key) {\n    if (!this.cache.has(key)) return -1;\n    const val = this.cache.get(key);\n    this.cache.delete(key);\n    this.cache.set(key, val);\n    return val;\n  }\n  put(key, val) {\n    if (this.cache.has(key)) this.cache.delete(key);\n    else if (this.cache.size >= this.capacity) this.cache.delete(this.cache.keys().next().value);\n    this.cache.set(key, val);\n  }\n}`,
    solutionExplanation: "JavaScript's Map preserves insertion order. To mark a key as 'recently used', delete it and re-insert it (moves to end). The LRU item is always the first key. This gives O(1) average for all operations.",
    hints: ["JavaScript's Map remembers insertion order", "When you access a key, delete and re-add it to mark it as most recently used"],
    tags: ["cache", "Map", "O(1)"], estimatedMinutes: 25,
  },
];

// ── Functional Programming ────────────────────────────────────────────────────
export const FUNCTIONAL_EXERCISES: Exercise[] = [
  {
    id: "compose",
    format: "solve",
    tier: 2, category: "functional",
    title: "Compose",
    tagline: "pipe() but right to left.",
    description: "Write `compose(...fns)` that applies functions right to left. `compose(f, g)(x)` is the same as `f(g(x))`.",
    why: "Compose is the mathematical standard. pipe() runs left-to-right (human readable), compose() runs right-to-left (mathematical notation). Knowing both is table stakes in functional JS.",
    analogy: "compose(f, g)(x) = f(g(x)) — read it inside-out, like nested functions.",
    examples: [
      { input: "const transform = compose(x => x * 2, x => x + 1);\ntransform(3)", output: "8", note: "3+1=4, 4*2=8 — g runs first" },
    ],
    starterCode: `function compose(...fns) {\n  // right to left — opposite of pipe\n}`,
    functionName: "compose",
    testCases: [
      { args: [(x: number) => x * 2, (x: number) => x + 1], expected: 8, label: "compose(×2, +1)(3) = 8" },
    ],
    solution: `function compose(...fns) {\n  return function(value) {\n    return fns.reduceRight((acc, fn) => fn(acc), value);\n  };\n}`,
    solutionExplanation: "Same as pipe but use reduceRight instead of reduce, so functions apply from right to left.",
    hints: ["It's the same as pipe — except use reduceRight instead of reduce"],
    tags: ["functional", "composition", "reduceRight"], estimatedMinutes: 8,
  },
  {
    id: "curry",
    format: "solve",
    tier: 3, category: "functional",
    title: "Curry",
    tagline: "One argument at a time.",
    description: "Write `curry(fn)` that transforms any multi-argument function into a series of single-argument functions. `curry(add)(1)(2)(3)` should equal `add(1, 2, 3)`.",
    why: "Currying is how you create specialized functions from general ones. It powers partial application, function pipelines, and the entire Haskell ecosystem. React hooks use this pattern.",
    analogy: "Instead of ordering a full burger at once, you make one decision at a time: first the bun, then the patty, then the toppings.",
    examples: [
      { input: "const add = (a, b, c) => a + b + c;\ncurry(add)(1)(2)(3)", output: "6" },
      { input: "curry(add)(1, 2)(3)", output: "6", note: "partial application also works" },
    ],
    starterCode: `function curry(fn) {\n  // return a curried version of fn\n}`,
    functionName: "curry",
    testCases: [
      { args: [(a: number, b: number, c: number) => a + b + c], expected: 6, label: "curry(add)(1)(2)(3) = 6" },
    ],
    solution: `function curry(fn) {\n  return function curried(...args) {\n    if (args.length >= fn.length) {\n      return fn.apply(this, args);\n    }\n    return function(...moreArgs) {\n      return curried.apply(this, args.concat(moreArgs));\n    };\n  };\n}`,
    solutionExplanation: "Check if enough arguments have accumulated (args.length >= fn.length). If yes, call the original function. If not, return a new function that collects more arguments.",
    hints: ["fn.length tells you how many arguments fn expects", "Accumulate arguments until you have enough, then call the original"],
    tags: ["curry", "closure", "functional"], estimatedMinutes: 20,
  },
  {
    id: "once",
    format: "solve",
    tier: 2, category: "functional",
    title: "Once",
    tagline: "Run it once. Ignore every call after.",
    description: "Write `once(fn)` that returns a version of the function that can only be called once. Subsequent calls return the result of the first call without re-executing.",
    why: "Initialization code, analytics events, payment processing — there are many cases where a function must only run once. This is also a great closure exercise.",
    examples: [
      { input: "const init = once(() => { console.log('running'); return 42; });\ninit() // logs 'running', returns 42\ninit() // returns 42, does NOT log again", output: "42 (both times)" },
    ],
    starterCode: `function once(fn) {\n  // return a function that only runs fn once\n}`,
    functionName: "once",
    testCases: [
      { args: [() => 42], expected: 42, label: "once(fn)() returns fn's value" },
    ],
    solution: `function once(fn) {\n  let called = false;\n  let result;\n  return function(...args) {\n    if (!called) {\n      called = true;\n      result = fn.apply(this, args);\n    }\n    return result;\n  };\n}`,
    solutionExplanation: "Use a closure with a 'called' flag. After the first invocation, store the result and return it for every subsequent call without re-executing fn.",
    hints: ["Use a closure — a variable that persists between calls", "A boolean 'called' flag + storing the result is all you need"],
    tags: ["closure", "once", "functional"], estimatedMinutes: 10,
  },
  {
    id: "partial-apply",
    format: "solve",
    tier: 3, category: "functional",
    title: "Partial Application",
    tagline: "Lock in some arguments, leave the rest open.",
    description: "Write `partial(fn, ...presetArgs)` that returns a new function with some arguments already filled in. Calling the returned function with the remaining arguments completes the call.",
    why: "Partial application is how you create specialized utility functions from general ones. It's the basis of event handlers, middleware, and configuration-driven design.",
    analogy: "You pre-fill part of a form, then hand it to someone else to complete the rest.",
    examples: [
      { input: "const multiply = (a, b) => a * b;\nconst double = partial(multiply, 2);\ndouble(5)", output: "10" },
      { input: "const add = (a, b, c) => a + b + c;\nconst add10 = partial(add, 10);\nadd10(1, 2)", output: "13" },
    ],
    starterCode: `function partial(fn, ...presetArgs) {\n  // return a function with presetArgs already filled in\n}`,
    functionName: "partial",
    testCases: [
      { args: [(a: number, b: number) => a * b, 2], expected: 10, label: "partial(multiply, 2)(5) = 10" },
    ],
    solution: `function partial(fn, ...presetArgs) {\n  return function(...laterArgs) {\n    return fn(...presetArgs, ...laterArgs);\n  };\n}`,
    solutionExplanation: "Capture the preset arguments in a closure, then spread both preset and later args when calling the original function.",
    hints: ["Use rest params to capture presetArgs", "Spread both sets of args when calling fn: fn(...presetArgs, ...laterArgs)"],
    tags: ["partial", "closure", "functional"], estimatedMinutes: 10,
  },
  {
    id: "flatten-map",
    format: "solve",
    tier: 2, category: "functional",
    title: "Implement flatMap",
    tagline: "Map then flatten — without using flatMap.",
    description: "Write `flatMap(arr, fn)` that maps each element with `fn`, then flattens the result one level. Do not use `Array.prototype.flatMap`.",
    why: "flatMap is one of the most useful functional operations — it powers 'expand then flatten' transforms like splitting sentences into words or expanding relationships.",
    examples: [
      { input: "flatMap([1, 2, 3], n => [n, n * 2])", output: "[1, 2, 2, 4, 3, 6]" },
      { input: "flatMap(['a b', 'c d'], s => s.split(' '))", output: "['a', 'b', 'c', 'd']" },
    ],
    starterCode: `function flatMap(arr, fn) {\n  // no Array.flatMap\n}`,
    functionName: "flatMap",
    testCases: [
      { args: [[1, 2, 3], (n: number) => [n, n * 2]], expected: [1, 2, 2, 4, 3, 6], label: "expand each to pair" },
      { args: [["a b", "c d"], (s: string) => s.split(" ")], expected: ["a", "b", "c", "d"], label: "split strings" },
      { args: [[], (n: number) => [n]], expected: [], label: "empty array", hidden: true },
    ],
    solution: `function flatMap(arr, fn) {\n  return arr.reduce((acc, item) => acc.concat(fn(item)), []);\n}`,
    solutionExplanation: "Use reduce to build the result. For each item, call fn(item) which returns an array, then concat it. concat flattens one level.",
    hints: ["Map first, then flatten — or combine both using reduce", "concat flattens one level"],
    tags: ["flatMap", "reduce", "functional"], estimatedMinutes: 8,
  },
];

// ── Async ─────────────────────────────────────────────────────────────────────
export const ASYNC_EXERCISES: Exercise[] = [
  {
    id: "sleep",
    format: "solve",
    tier: 2, category: "async",
    title: "Sleep",
    tagline: "Pause execution for N milliseconds.",
    description: "Write `sleep(ms)` that returns a Promise which resolves after `ms` milliseconds. It must work with `await`.",
    why: "sleep() is a tool you'll reach for in tests, demos, retry logic, and rate limiting. More importantly, it forces you to understand how Promise + setTimeout work together.",
    examples: [
      { input: "await sleep(1000); // pauses for 1 second", output: "continues after 1000ms" },
    ],
    starterCode: `function sleep(ms) {\n  // return a Promise that resolves after ms milliseconds\n}`,
    functionName: "sleep",
    testCases: [
      { args: [0], expected: undefined, label: "sleep(0) resolves" },
    ],
    solution: `function sleep(ms) {\n  return new Promise(resolve => setTimeout(resolve, ms));\n}`,
    solutionExplanation: "Wrap setTimeout in a Promise. When the timeout fires, call resolve(). Awaiting this Promise pauses execution for the specified duration.",
    hints: ["new Promise((resolve, reject) => ...)", "Pass resolve directly as the setTimeout callback"],
    tags: ["async", "Promise", "setTimeout"], estimatedMinutes: 8,
  },
  {
    id: "promise-all-impl",
    format: "solve",
    tier: 3, category: "async",
    title: "Implement Promise.all",
    tagline: "Run everything at once. Wait for all.",
    description: "Write `promiseAll(promises)` that takes an array of Promises and returns a new Promise that resolves with an array of all results in order. If any promise rejects, reject immediately with that reason.",
    why: "Understanding Promise.all from the inside makes you dangerous with async code. You'll spot race conditions, understand why order is preserved, and debug parallel fetches confidently.",
    analogy: "You order food, coffee, and dessert at once. You don't eat until everything arrives. If the kitchen cancels any item, the whole order is off.",
    examples: [
      { input: "promiseAll([Promise.resolve(1), Promise.resolve(2), Promise.resolve(3)])", output: "[1, 2, 3]" },
      { input: "promiseAll([Promise.resolve(1), Promise.reject('error')])", output: "rejects with 'error'" },
    ],
    starterCode: `function promiseAll(promises) {\n  return new Promise((resolve, reject) => {\n    // your code here\n  });\n}`,
    functionName: "promiseAll",
    testCases: [
      { args: [[Promise.resolve(1), Promise.resolve(2), Promise.resolve(3)]], expected: [1, 2, 3], label: "resolves all in order" },
    ],
    solution: `function promiseAll(promises) {\n  return new Promise((resolve, reject) => {\n    const results = [];\n    let remaining = promises.length;\n    if (remaining === 0) return resolve([]);\n    promises.forEach((p, i) => {\n      Promise.resolve(p).then(val => {\n        results[i] = val;\n        if (--remaining === 0) resolve(results);\n      }).catch(reject);\n    });\n  });\n}`,
    solutionExplanation: "Track how many promises remain. Store results at the original index (preserves order). When remaining hits 0, resolve with results. Any rejection immediately rejects the outer promise.",
    hints: ["Store results at the original index to preserve order", "Count remaining promises — when it hits 0, resolve with results"],
    tags: ["async", "Promise", "parallel"], estimatedMinutes: 20,
  },
  {
    id: "retry",
    format: "solve",
    tier: 3, category: "async",
    title: "Retry with Backoff",
    tagline: "Try again. Wait longer each time.",
    description: "Write `retry(fn, retries, delay)` that calls `fn()` (an async function). If it throws, wait `delay`ms and try again. Double the delay after each failure. Reject with the last error after all retries are exhausted.",
    why: "Every production system retries failed network calls. Exponential backoff prevents hammering a struggling server. This is not taught in college but is in every production codebase.",
    analogy: "You knock on a door. No answer? Wait 1 second and knock again. Still no answer? Wait 2 seconds. Then 4. Then give up.",
    examples: [
      { input: "retry(fetchUser, 3, 1000)", output: "resolves on success, or rejects after 3 tries" },
    ],
    starterCode: `async function retry(fn, retries, delay) {\n  // try fn(), retry with exponential backoff\n}`,
    functionName: "retry",
    testCases: [
      { args: [async () => 42, 3, 0], expected: 42, label: "succeeds immediately" },
    ],
    solution: `async function retry(fn, retries, delay) {\n  try {\n    return await fn();\n  } catch (err) {\n    if (retries <= 0) throw err;\n    await new Promise(r => setTimeout(r, delay));\n    return retry(fn, retries - 1, delay * 2);\n  }\n}`,
    solutionExplanation: "Try the function. On failure, if retries remain, wait the delay then recurse with retries-1 and doubled delay. When retries is 0, rethrow the error.",
    hints: ["Recursive approach: try, on fail recurse with (retries - 1, delay * 2)", "sleep(delay) before retrying"],
    tags: ["async", "retry", "backoff"], estimatedMinutes: 15,
  },
];

// ── Regex ─────────────────────────────────────────────────────────────────────
export const REGEX_EXERCISES: Exercise[] = [
  {
    id: "extract-numbers",
    format: "solve",
    tier: 2, category: "regex",
    title: "Extract All Numbers",
    tagline: "Pull every number out of a string.",
    description: "Write `extractNumbers(str)` that returns an array of all numbers (integers and decimals) found in the string.",
    why: "Extracting structured data from unstructured text is one of the most common tasks in backend work. Prices, IDs, measurements — they all need to be pulled from strings.",
    examples: [
      { input: "extractNumbers('I paid $19.99 and $5 for 2 items')", output: "[19.99, 5, 2]" },
      { input: "extractNumbers('no numbers here')", output: "[]" },
    ],
    starterCode: `function extractNumbers(str) {\n  // return all numbers found in the string\n}`,
    functionName: "extractNumbers",
    testCases: [
      { args: ["I paid $19.99 and $5 for 2 items"], expected: [19.99, 5, 2], label: "dollars and integers" },
      { args: ["no numbers here"], expected: [], label: "no numbers → empty array" },
      { args: ["room 101, floor 3, apt 4B"], expected: [101, 3, 4], label: "mixed content" },
      { args: ["0.5 1.0 2.5"], expected: [0.5, 1.0, 2.5], label: "decimals", hidden: true },
    ],
    solution: `function extractNumbers(str) {\n  const matches = str.match(/\\d+\\.?\\d*/g);\n  return matches ? matches.map(Number) : [];\n}`,
    solutionExplanation: "The regex \\d+\\.?\\d* matches one or more digits, optionally followed by a decimal point and more digits. match() with the 'g' flag returns all matches. Map to Number to convert strings.",
    hints: ["String.match(regex) with the 'g' flag returns all matches", "\\d+ matches digits, \\.? matches an optional period"],
    tags: ["regex", "match", "numbers"], estimatedMinutes: 10,
  },
  {
    id: "validate-email",
    format: "solve",
    tier: 2, category: "regex",
    title: "Validate an Email",
    tagline: "Is this a real email address format?",
    description: "Write `isValidEmail(str)` that returns `true` if the string looks like a valid email. Rule: one `@`, a domain with at least one `.`, no spaces, valid characters only.",
    why: "Every form with an email field needs this. Understanding regex validation makes you faster at form work and stops you from reaching for libraries for simple checks.",
    examples: [
      { input: "isValidEmail('user@example.com')", output: "true" },
      { input: "isValidEmail('user@example')", output: "false", note: "no TLD" },
      { input: "isValidEmail('not an email')", output: "false" },
    ],
    starterCode: `function isValidEmail(str) {\n  // validate email format using regex\n}`,
    functionName: "isValidEmail",
    testCases: [
      { args: ["user@example.com"], expected: true, label: "basic valid email" },
      { args: ["user@example"], expected: false, label: "missing TLD" },
      { args: ["not an email"], expected: false, label: "no @ sign" },
      { args: ["@example.com"], expected: false, label: "nothing before @" },
      { args: ["user@.com"], expected: false, label: "no domain name" },
      { args: ["user.name+tag@sub.example.co.uk"], expected: true, label: "complex valid email", hidden: true },
    ],
    solution: `function isValidEmail(str) {\n  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(str);\n}`,
    solutionExplanation: "The pattern: start, one or more non-space non-@ chars, @, one or more non-space non-@ chars, literal dot, one or more non-space non-@ chars, end. Simple but covers the common cases.",
    hints: ["The pattern needs: something@something.something", "Use ^ and $ to match the full string", "[^\\s@]+ matches 'anything except space and @'"],
    tags: ["regex", "validation", "email"], estimatedMinutes: 12,
  },
  {
    id: "strip-html",
    format: "solve",
    tier: 2, category: "regex",
    title: "Strip HTML Tags",
    tagline: "Extract plain text from HTML.",
    description: "Write `stripHtml(str)` that removes all HTML tags and returns the plain text content.",
    why: "Content from CMSs, APIs, and user input often comes with HTML tags mixed in. Stripping them is a constant need.",
    examples: [
      { input: "stripHtml('<p>Hello <strong>world</strong></p>')", output: "'Hello world'" },
      { input: "stripHtml('<a href=\"/\">Click here</a>')", output: "'Click here'" },
    ],
    starterCode: `function stripHtml(str) {\n  // remove all HTML tags\n}`,
    functionName: "stripHtml",
    testCases: [
      { args: ["<p>Hello <strong>world</strong></p>"], expected: "Hello world", label: "nested tags" },
      { args: ['<a href="/">Click here</a>'], expected: "Click here", label: "tag with attribute" },
      { args: ["No tags here"], expected: "No tags here", label: "plain text passthrough" },
      { args: ["<div><p>Nested</p></div>"], expected: "Nested", label: "deeply nested", hidden: true },
    ],
    solution: `function stripHtml(str) {\n  return str.replace(/<[^>]*>/g, '');\n}`,
    solutionExplanation: "The regex <[^>]*> matches an opening angle bracket, any characters that aren't a closing bracket, then a closing bracket — which is any HTML tag.",
    hints: ["HTML tags look like <...> — match everything between angle brackets", "<[^>]*> matches any tag"],
    tags: ["regex", "replace", "HTML"], estimatedMinutes: 8,
  },
  {
    id: "url-slug",
    format: "solve",
    tier: 2, category: "regex",
    title: "Generate a URL Slug",
    tagline: "Turn a title into a clean URL.",
    description: "Write `slugify(str)` that converts a string into a URL-friendly slug: lowercase, spaces and special characters replaced by hyphens, no leading/trailing hyphens, no consecutive hyphens.",
    why: "Every blog, CMS, and product page generates slugs. Building it yourself teaches you real regex replacement chaining.",
    examples: [
      { input: "slugify('Hello World!')", output: "'hello-world'" },
      { input: "slugify('  The Forge -- Academy  ')", output: "'the-forge-academy'" },
    ],
    starterCode: `function slugify(str) {\n  // lowercase, replace non-alphanumeric with hyphens, clean up\n}`,
    functionName: "slugify",
    testCases: [
      { args: ["Hello World!"], expected: "hello-world", label: "basic slugify" },
      { args: ["  The Forge -- Academy  "], expected: "the-forge-academy", label: "extra spaces and hyphens" },
      { args: ["It's a TEST"], expected: "it-s-a-test", label: "apostrophe becomes hyphen" },
      { args: ["already-a-slug"], expected: "already-a-slug", label: "passthrough", hidden: true },
    ],
    solution: `function slugify(str) {\n  return str\n    .toLowerCase()\n    .replace(/[^a-z0-9]+/g, '-')\n    .replace(/^-+|-+$/g, '');\n}`,
    solutionExplanation: "Three steps: lowercase everything, replace any sequence of non-alphanumeric chars with a single hyphen, then trim leading/trailing hyphens.",
    hints: ["Chain multiple .replace() calls", "[^a-z0-9]+ matches anything that isn't a letter or digit"],
    tags: ["regex", "strings", "URL"], estimatedMinutes: 10,
  },
];

// ── More Algorithms ──────────────────────────────────────────────────────────
export const MORE_ALGORITHM_EXERCISES: Exercise[] = [
  {
    id: "fibonacci-dp",
    format: "solve",
    tier: 3, category: "algorithms",
    title: "Fibonacci — Dynamic Programming",
    tagline: "O(n) instead of O(2^n).",
    description: "Write `fib(n)` that returns the nth Fibonacci number. Implement it with dynamic programming (bottom-up) — not naive recursion. fib(0)=0, fib(1)=1, fib(2)=1, fib(3)=2...",
    why: "The naive recursive solution is O(2^n) and melts at n=40. DP reduces it to O(n). This is the gateway to understanding memoization, tabulation, and why CS teaches it first.",
    analogy: "Instead of recalculating the same sub-problems over and over, write each answer on a notepad the first time and look it up after.",
    examples: [
      { input: "fib(0)", output: "0" },
      { input: "fib(10)", output: "55" },
      { input: "fib(40)", output: "102334155 (try this with naive recursion — it will lag)" },
    ],
    starterCode: `function fib(n) {\n  // bottom-up DP — no naive recursion\n}`,
    functionName: "fib",
    testCases: [
      { args: [0], expected: 0, label: "fib(0) = 0" },
      { args: [1], expected: 1, label: "fib(1) = 1" },
      { args: [10], expected: 55, label: "fib(10) = 55" },
      { args: [40], expected: 102334155, label: "fib(40) — fast or bust" },
      { args: [2], expected: 1, label: "fib(2) = 1", hidden: true },
    ],
    solution: `function fib(n) {\n  if (n <= 1) return n;\n  let a = 0, b = 1;\n  for (let i = 2; i <= n; i++) {\n    [a, b] = [b, a + b];\n  }\n  return b;\n}`,
    solutionExplanation: "Keep only two variables (a and b). Each iteration, shift: a becomes b, b becomes a+b. After n-1 iterations, b is the answer. O(n) time, O(1) space.",
    hints: ["You only need the last two numbers to compute the next", "Swap: [a, b] = [b, a + b]"],
    tags: ["DP", "fibonacci", "O(n)"], estimatedMinutes: 12,
  },
  {
    id: "max-subarray",
    format: "solve",
    tier: 4, category: "algorithms",
    title: "Maximum Subarray",
    tagline: "Find the contiguous subarray with the largest sum.",
    description: "Write `maxSubarray(nums)` that returns the sum of the contiguous subarray with the largest total. Solve it in O(n) using Kadane's algorithm.",
    why: "Kadane's algorithm is one of the most elegant O(n) solutions. It teaches you greedy thinking: keep what's useful, discard what hurts you. Appears in financial analysis, signal processing, and interviews constantly.",
    analogy: "Walking a hill — at each step, decide: is it better to continue my current path, or start fresh from here?",
    examples: [
      { input: "maxSubarray([-2,1,-3,4,-1,2,1,-5,4])", output: "6", note: "[4,-1,2,1] = 6" },
      { input: "maxSubarray([1])", output: "1" },
      { input: "maxSubarray([-1,-2,-3])", output: "-1", note: "all negative — pick the least bad" },
    ],
    starterCode: `function maxSubarray(nums) {\n  // Kadane's algorithm — O(n)\n}`,
    functionName: "maxSubarray",
    testCases: [
      { args: [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], expected: 6, label: "classic example" },
      { args: [[1]], expected: 1, label: "single element" },
      { args: [[-1, -2, -3]], expected: -1, label: "all negative" },
      { args: [[5, 4, -1, 7, 8]], expected: 23, label: "all contribute", hidden: true },
    ],
    solution: `function maxSubarray(nums) {\n  let maxSum = nums[0], curr = nums[0];\n  for (let i = 1; i < nums.length; i++) {\n    curr = Math.max(nums[i], curr + nums[i]);\n    maxSum = Math.max(maxSum, curr);\n  }\n  return maxSum;\n}`,
    solutionExplanation: "At each position: either extend the previous subarray (curr + nums[i]) or start fresh (nums[i]) — take the max. Track the running max across all positions.",
    hints: ["At each step: should I extend the current subarray or start a new one?", "curr = Math.max(nums[i], curr + nums[i])"],
    tags: ["Kadane's", "greedy", "DP"], estimatedMinutes: 20,
  },
  {
    id: "valid-anagram",
    format: "solve",
    tier: 2, category: "algorithms",
    title: "Valid Anagram",
    tagline: "Same letters, different order?",
    description: "Write `isAnagram(s, t)` that returns `true` if `t` is an anagram of `s` (contains the same characters in any order). Ignore case.",
    why: "Anagram detection is a pure frequency-map problem. Solving it teaches you the pattern that applies to 50+ interview problems: compare distributions, not sequences.",
    analogy: "'silent' and 'listen' have identical letters — just rearranged.",
    examples: [
      { input: "isAnagram('anagram', 'nagaram')", output: "true" },
      { input: "isAnagram('rat', 'car')", output: "false" },
    ],
    starterCode: `function isAnagram(s, t) {\n  // your code here\n}`,
    functionName: "isAnagram",
    testCases: [
      { args: ["anagram", "nagaram"], expected: true, label: "classic anagram" },
      { args: ["rat", "car"], expected: false, label: "not anagram" },
      { args: ["a", "a"], expected: true, label: "single same char" },
      { args: ["ab", "a"], expected: false, label: "different lengths" },
      { args: ["Listen", "Silent"], expected: true, label: "case insensitive", hidden: true },
    ],
    solution: `function isAnagram(s, t) {\n  if (s.length !== t.length) return false;\n  const count = {};\n  for (const ch of s.toLowerCase()) count[ch] = (count[ch] ?? 0) + 1;\n  for (const ch of t.toLowerCase()) {\n    if (!count[ch]) return false;\n    count[ch]--;\n  }\n  return true;\n}`,
    solutionExplanation: "Count character frequencies in s, then decrement for each char in t. If any count goes to 0 or below, not an anagram. Length check first for efficiency.",
    hints: ["Early exit: different lengths = not anagram", "Build a frequency map of s, then check t against it"],
    tags: ["frequency-map", "strings", "anagram"], estimatedMinutes: 10,
  },
  {
    id: "climbing-stairs",
    format: "solve",
    tier: 4, category: "algorithms",
    title: "Climbing Stairs",
    tagline: "How many ways to reach the top?",
    description: "Write `climbStairs(n)` that counts the number of distinct ways to climb n stairs, taking 1 or 2 steps at a time.",
    why: "This is the gateway DP problem. It looks like a puzzle but it's Fibonacci in disguise. Recognizing this teaches you to spot DP patterns in the wild.",
    analogy: "You're at step 0. You can hop 1 or 2 stairs at a time. How many different routes reach step n?",
    examples: [
      { input: "climbStairs(2)", output: "2", note: "(1+1) or (2)" },
      { input: "climbStairs(3)", output: "3", note: "(1+1+1), (1+2), (2+1)" },
      { input: "climbStairs(5)", output: "8" },
    ],
    starterCode: `function climbStairs(n) {\n  // dynamic programming\n}`,
    functionName: "climbStairs",
    testCases: [
      { args: [1], expected: 1, label: "1 stair = 1 way" },
      { args: [2], expected: 2, label: "2 stairs = 2 ways" },
      { args: [3], expected: 3, label: "3 stairs = 3 ways" },
      { args: [5], expected: 8, label: "5 stairs = 8 ways" },
      { args: [10], expected: 89, label: "10 stairs = 89 ways", hidden: true },
    ],
    solution: `function climbStairs(n) {\n  if (n <= 2) return n;\n  let a = 1, b = 2;\n  for (let i = 3; i <= n; i++) [a, b] = [b, a + b];\n  return b;\n}`,
    solutionExplanation: "ways(n) = ways(n-1) + ways(n-2) — you got to step n from either step n-1 (one step) or step n-2 (two steps). It's Fibonacci starting from 1, 2.",
    hints: ["How many ways to reach step n? You came from step n-1 or step n-2", "This is Fibonacci — ways(n) = ways(n-1) + ways(n-2)"],
    tags: ["DP", "Fibonacci", "counting"], estimatedMinutes: 15,
  },
  {
    id: "rotate-array",
    format: "solve",
    tier: 2, category: "algorithms",
    title: "Rotate Array",
    tagline: "Shift every element k positions right.",
    description: "Write `rotateArray(nums, k)` that rotates the array to the right by k steps. Do it in-place (modify the array, return it). Handle k larger than the array length.",
    why: "Rotation problems appear in carousel UI, scheduling, cryptography. The elegant three-reverse solution teaches you how clever algorithm design eliminates extra space.",
    examples: [
      { input: "rotateArray([1,2,3,4,5,6,7], 3)", output: "[5,6,7,1,2,3,4]" },
      { input: "rotateArray([1,2], 5)", output: "[2,1]", note: "k=5 is same as k=1 for length-2 array" },
    ],
    starterCode: `function rotateArray(nums, k) {\n  // rotate in-place, return the modified array\n}`,
    functionName: "rotateArray",
    testCases: [
      { args: [[1, 2, 3, 4, 5, 6, 7], 3], expected: [5, 6, 7, 1, 2, 3, 4], label: "rotate 3 right" },
      { args: [[-1, -100, 3, 99], 2], expected: [3, 99, -1, -100], label: "rotate 2 right" },
      { args: [[1, 2], 5], expected: [2, 1], label: "k > length" },
      { args: [[1], 0], expected: [1], label: "k=0", hidden: true },
    ],
    solution: `function rotateArray(nums, k) {\n  const n = nums.length;\n  k = k % n;\n  reverse(nums, 0, n - 1);\n  reverse(nums, 0, k - 1);\n  reverse(nums, k, n - 1);\n  return nums;\n}\nfunction reverse(arr, l, r) {\n  while (l < r) { [arr[l], arr[r]] = [arr[r], arr[l]]; l++; r--; }\n}`,
    solutionExplanation: "Three reverses trick: (1) reverse whole array, (2) reverse first k elements, (3) reverse remaining n-k elements. Works in O(n) with O(1) space.",
    hints: ["k = k % nums.length handles k > length", "There's a clever 3-step reverse approach that works in O(n) and O(1) space"],
    tags: ["array", "in-place", "two-pointers"], estimatedMinutes: 15,
  },
  {
    id: "longest-common-prefix",
    format: "solve",
    tier: 2, category: "algorithms",
    title: "Longest Common Prefix",
    tagline: "What do all strings start with?",
    description: "Write `longestCommonPrefix(strs)` that returns the longest prefix shared by all strings in the array. Return an empty string if none.",
    why: "Prefix matching is how autocomplete, URL routing, and file system path matching work. The pattern is more useful than it looks.",
    examples: [
      { input: "longestCommonPrefix(['flower','flow','flight'])", output: "'fl'" },
      { input: "longestCommonPrefix(['dog','racecar','car'])", output: "''", note: "no common prefix" },
    ],
    starterCode: `function longestCommonPrefix(strs) {\n  // your code here\n}`,
    functionName: "longestCommonPrefix",
    testCases: [
      { args: [["flower", "flow", "flight"]], expected: "fl", label: "'fl' is common" },
      { args: [["dog", "racecar", "car"]], expected: "", label: "no common prefix" },
      { args: [["interspecies", "interstellar", "interstate"]], expected: "inters", label: "longer prefix" },
      { args: [["a"]], expected: "a", label: "single string", hidden: true },
      { args: [["", "b"]], expected: "", label: "empty string", hidden: true },
    ],
    solution: `function longestCommonPrefix(strs) {\n  if (!strs.length) return '';\n  let prefix = strs[0];\n  for (let i = 1; i < strs.length; i++) {\n    while (!strs[i].startsWith(prefix)) prefix = prefix.slice(0, -1);\n    if (!prefix) return '';\n  }\n  return prefix;\n}`,
    solutionExplanation: "Start with the first string as the full potential prefix. For each subsequent string, shorten the prefix until it matches the start. If it empties, return ''.",
    hints: ["Start with strs[0] as the prefix, then shrink it", "Trim one character at a time until strs[i].startsWith(prefix)"],
    tags: ["strings", "prefix"], estimatedMinutes: 10,
  },
];

export const ALL_EXTRA_EXERCISES: Exercise[] = [
  ...DATA_STRUCTURE_EXERCISES,
  ...FUNCTIONAL_EXERCISES,
  ...ASYNC_EXERCISES,
  ...REGEX_EXERCISES,
  ...MORE_ALGORITHM_EXERCISES,
];
