export function downloadMarkdown(title: string, content: string): void {
  const header = `# ${title}\n\n*Generated by 13 Moon Forge — 13moonforge.ai*\n\n---\n\n`;
  const blob = new Blob([header + content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${slugify(title)}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadPDF(title: string, content: string): void {
  const win = window.open("", "_blank");
  if (!win) return;
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
<title>${escHtml(title)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 700px; margin: 60px auto; padding: 0 24px; color: #111; line-height: 1.7; }
  h1 { font-size: 1.6rem; font-weight: 900; margin-bottom: 4px; }
  .meta { color: #888; font-size: 0.8rem; margin-bottom: 32px; }
  .content { white-space: pre-wrap; font-size: 0.95rem; }
  footer { margin-top: 48px; border-top: 1px solid #eee; padding-top: 16px; color: #aaa; font-size: 0.75rem; }
  @media print { body { margin: 24px; } }
</style>
</head><body>
<h1>${escHtml(title)}</h1>
<div class="meta">Generated by 13 Moon Forge &mdash; 13moonforge.ai &mdash; ${new Date().toLocaleDateString()}</div>
<div class="content">${escHtml(content)}</div>
<footer>13 Moon Forge &mdash; Built for the working man.</footer>
<script>window.onload = () => { window.print(); setTimeout(() => window.close(), 500); }<\/script>
</body></html>`;
  win.document.write(html);
  win.document.close();
}

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "forge-output";
}

function escHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
