uploads = []

[[generated]]
id = "dEssJgXNK-8hRV8XwFA7f"
uri = "file://artifacts/forge-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "wXoHGU6WaasEbgayl77BB"
uri = "file://screenshots/13moonforge-home.jpg"
type = "image"
title = "13 Moon Forge — Homepage Screenshot"

[[outputs]]
id = "YVVrhdpjhgpIKZ5WHQlO5"
uri = "file://screenshots/13moonforge-logo.jpg"
type = "image"
title = "13 Moon Forge — Logo"

[[outputs]]
id = "CpiQAV3exubzGjxxImCEC"
uri = "file://13-moon-forge-full-export.md"
type = "text"
title = "13 Moon Forge — Full Source Code Export (203 files)"
