import { Router } from "express";
import { db } from "@workspace/db";
import { projectsTable, pagesTable, pageRevisionsTable } from "@workspace/db";
import { eq, desc, sql, and } from "drizzle-orm";
import archiver from "archiver";

const router = Router();

// ─── Duplicate project ────────────────────────────────────────────────────────
router.post("/projects/:id/duplicate", async (req, res) => {
  const projectId = Number(req.params.id);
  if (isNaN(projectId)) return res.status(400).json({ error: "Invalid ID" });

  try {
    const [source] = await db.select().from(projectsTable).where(eq(projectsTable.id, projectId));
    if (!source) return res.status(404).json({ error: "Project not found" });

    const [newProject] = await db
      .insert(projectsTable)
      .values({
        name: `${source.name} (Copy)`,
        description: source.description,
        template: source.template,
        status: "draft",
      })
      .returning();

    const sourcePages = await db
      .select()
      .from(pagesTable)
      .where(eq(pagesTable.projectId, projectId))
      .orderBy(pagesTable.order);

    if (sourcePages.length > 0) {
      await db.insert(pagesTable).values(
        sourcePages.map((p) => ({
          projectId: newProject.id,
          title: p.title,
          slug: p.slug,
          content: p.content,
          order: p.order,
          metaTitle: p.metaTitle,
          metaDescription: p.metaDescription,
        }))
      );
    }

    res.status(201).json({ ...newProject, pageCount: sourcePages.length });
  } catch (err) {
    req.log.error({ err }, "Failed to duplicate project");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ─── Export project as ZIP ────────────────────────────────────────────────────
router.get("/projects/:id/export", async (req, res) => {
  const projectId = Number(req.params.id);
  if (isNaN(projectId)) return res.status(400).json({ error: "Invalid ID" });

  try {
    const [project] = await db.select().from(projectsTable).where(eq(projectsTable.id, projectId));
    if (!project) return res.status(404).json({ error: "Project not found" });

    const pages = await db
      .select()
      .from(pagesTable)
      .where(eq(pagesTable.projectId, projectId))
      .orderBy(pagesTable.order);

    const safeName = project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    res.setHeader("Content-Type", "application/zip");
    res.setHeader("Content-Disposition", `attachment; filename="${safeName}.zip"`);

    const archive = archiver("zip", { zlib: { level: 9 } });
    archive.on("error", (err) => { req.log.error({ err }, "Archive error"); res.end(); });
    archive.pipe(res);

    for (const page of pages) {
      const filename = page.slug === "home" ? "index.html" : `${page.slug}.html`;
      const html = page.content || `<!DOCTYPE html><html><head><title>${page.title}</title></head><body><h1>${page.title}</h1></body></html>`;
      archive.append(html, { name: filename });
    }

    // Add a simple README
    const readme = `# ${project.name}\n\nGenerated by The Forge.\n\n## Pages\n${pages.map(p => `- ${p.title} → ${p.slug === "home" ? "index.html" : p.slug + ".html"}`).join("\n")}\n\nOpen index.html in a browser to view your site.`;
    archive.append(readme, { name: "README.md" });

    await archive.finalize();
  } catch (err) {
    req.log.error({ err }, "Failed to export project");
    if (!res.headersSent) res.status(500).json({ error: "Internal server error" });
  }
});

// ─── Page revisions ───────────────────────────────────────────────────────────
router.get("/projects/:id/pages/:pageId/revisions", async (req, res) => {
  const projectId = Number(req.params.id);
  const pageId = Number(req.params.pageId);
  if (isNaN(projectId) || isNaN(pageId)) return res.status(400).json({ error: "Invalid params" });

  try {
    const revisions = await db
      .select()
      .from(pageRevisionsTable)
      .where(eq(pageRevisionsTable.pageId, pageId))
      .orderBy(desc(pageRevisionsTable.createdAt))
      .limit(10);

    res.json(revisions);
  } catch (err) {
    req.log.error({ err }, "Failed to list revisions");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.post("/projects/:id/pages/:pageId/revisions/:revisionId/restore", async (req, res) => {
  const projectId = Number(req.params.id);
  const pageId = Number(req.params.pageId);
  const revisionId = Number(req.params.revisionId);
  if (isNaN(projectId) || isNaN(pageId) || isNaN(revisionId)) return res.status(400).json({ error: "Invalid params" });

  try {
    const [revision] = await db
      .select()
      .from(pageRevisionsTable)
      .where(and(eq(pageRevisionsTable.id, revisionId), eq(pageRevisionsTable.pageId, pageId)));

    if (!revision) return res.status(404).json({ error: "Revision not found" });

    const [currentPage] = await db.select().from(pagesTable).where(
      and(eq(pagesTable.id, pageId), eq(pagesTable.projectId, projectId))
    );
    if (!currentPage) return res.status(404).json({ error: "Page not found" });

    // Save current as a new revision before restoring
    if (currentPage.content) {
      await db.insert(pageRevisionsTable).values({ pageId, content: currentPage.content });
    }

    // Restore
    const [updated] = await db
      .update(pagesTable)
      .set({ content: revision.content, updatedAt: new Date() })
      .where(and(eq(pagesTable.id, pageId), eq(pagesTable.projectId, projectId)))
      .returning();

    // Keep only last 10 revisions
    const allRevisions = await db
      .select({ id: pageRevisionsTable.id })
      .from(pageRevisionsTable)
      .where(eq(pageRevisionsTable.pageId, pageId))
      .orderBy(desc(pageRevisionsTable.createdAt));

    if (allRevisions.length > 10) {
      const toDelete = allRevisions.slice(10).map(r => r.id);
      await db.delete(pageRevisionsTable).where(sql`${pageRevisionsTable.id} = ANY(${toDelete})`);
    }

    res.json(updated);
  } catch (err) {
    req.log.error({ err }, "Failed to restore revision");
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
