import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import projectsRouter from "./projects";
import dashboardRouter from "./dashboard";
import forgeRouter from "./forge";
import extrasRouter from "./extras";
import paymentsRouter from "./payments";
import flintRouter from "./flint";
import moonIntegrationRouter from "./moonIntegration";
import deployRouter from "./deploy";
import githubRouter from "./github";
import gitlabRouter from "./gitlab";
import bitbucketRouter from "./bitbucket";
import { router as secretsRouter } from "./secrets";
import { router as adminRouter } from "./admin";
import connectionsRouter from "./connections";
import coolifyRouter from "./coolify";
import monitorRouter from "./monitor";
import computerAdvisorRouter from "./computer-advisor";
import screenCoachRouter from "./screen-coach";
import quotaRouter from "./quota";
import siteForgeRouter from "./site-forge";
import landingForgeRouter from "./landing-forge";
import computerFixRouter from "./computer-fix";
import { remoteRouter } from "./remote";
import workspaceRouter from "./workspace";
import ttsRouter from "./tts";
import antivirusRouter from "./antivirus";
import mailboxRouter from "./mailbox";
import emailInboundRouter from "./email-inbound";
import accountRouter from "./account";
import chatHistoryRouter from "./chatHistory";
import promptsRouter from "./prompts";
import moonUsageRouter from "./moonUsage";
import shareRouter from "./share";
import workspaceSearchRouter from "./workspaceSearch";
import forgeReportRouter from "./forgeReport";
import buildWithMeRouter from "./buildWithMe";
import memoryRouter from "./memory";
import pulseRouter from "./pulse";
import scoreRouter from "./score";
import referralRouter from "./referral";
import hetznerRouter from "./hetzner";
import mailScannerRouter from "./mail-scanner";
import debugTestRouter from "./debugTest";
import academyRouter from "./academy";
import gymRouter from "./gym";
import launchRouter from "./launch";
import databasesRouter from "./databases";
import cliRouter from "./cli";
import uptimeRouter from "./uptime";
import storageRouter from "./storage";
import emailGatewayRouter from "./email-gateway";
import aiGatewayRouter from "./ai-gateway";
import marketplaceRouter from "./marketplace";
import vaultRouter from "./vault";
import activityRouter from "./activity";
import deploysRouter from "./deploys";
import helpRouter from "./help";
import agentRouter from "./agent";
import moonsRouter from "./moons";
import inspectorRouter from "./inspector";
import cliInspectRouter from "./cli-inspect";
import inspectorAppsRouter from "./inspector-apps";
import inspectorAdvancedRouter from "./inspector-advanced";
import bugCheckerRouter from "./bug-checker";
import appHealthRouter from "./app-health";
import domainsRouter from "./domains";
import codeVaultRouter from "./code-vault-route";
import appLogsRouter from "./app-logs";
import agentBridgeRouter from "./agent-bridge";
import autoSyncRouter from "./auto-sync";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(projectsRouter);
router.use(dashboardRouter);
router.use(forgeRouter);
router.use(extrasRouter);
router.use(paymentsRouter);
router.use(flintRouter);
router.use(moonIntegrationRouter);
router.use(deployRouter);
router.use(githubRouter);
router.use(gitlabRouter);
router.use(bitbucketRouter);
router.use(secretsRouter);
router.use(adminRouter);
router.use(connectionsRouter);
router.use(coolifyRouter);
router.use(monitorRouter);
router.use(computerAdvisorRouter);
router.use(screenCoachRouter);
router.use(quotaRouter);
router.use(siteForgeRouter);
router.use(landingForgeRouter);
router.use(computerFixRouter);
router.use("/remote", remoteRouter);
router.use(workspaceRouter);
router.use(ttsRouter);
router.use(antivirusRouter);
router.use(mailboxRouter);
router.use(emailInboundRouter);
router.use(accountRouter);
router.use(chatHistoryRouter);
router.use(promptsRouter);
router.use(moonUsageRouter);
router.use(shareRouter);
router.use(workspaceSearchRouter);
router.use(forgeReportRouter);
router.use(buildWithMeRouter);
router.use(memoryRouter);
router.use(pulseRouter);
router.use(scoreRouter);
router.use(referralRouter);
router.use(hetznerRouter);
router.use(mailScannerRouter);
router.use(debugTestRouter);
router.use(academyRouter);
router.use(gymRouter);
router.use(launchRouter);
router.use(databasesRouter);
router.use(cliRouter);
router.use(uptimeRouter);
router.use(storageRouter);
router.use(emailGatewayRouter);
router.use(aiGatewayRouter);
router.use(marketplaceRouter);
router.use(vaultRouter);
router.use(activityRouter);
router.use(deploysRouter);
router.use(helpRouter);
router.use(agentRouter);
router.use(moonsRouter);
router.use(inspectorRouter);
router.use(cliInspectRouter);
router.use(inspectorAppsRouter);
router.use(inspectorAdvancedRouter);
router.use(bugCheckerRouter);
router.use(appHealthRouter);
router.use(domainsRouter);
router.use(codeVaultRouter);
router.use(appLogsRouter);
router.use(agentBridgeRouter);
router.use(autoSyncRouter);

export default router;
