import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import dashboardRouter from "./dashboard";
import forgeRouter from "./forge";
import extrasRouter from "./extras";
import paymentsRouter from "./payments";
import flintRouter from "./flint";
import moonIntegrationRouter from "./moonIntegration";
import deployRouter from "./deploy";
import githubRouter from "./github";
import gitlabRouter from "./gitlab";
import bitbucketRouter from "./bitbucket";
import { router as secretsRouter } from "./secrets";
import { router as adminRouter } from "./admin";
import connectionsRouter from "./connections";
import coolifyRouter from "./coolify";
import monitorRouter from "./monitor";
import computerAdvisorRouter from "./computer-advisor";
import screenCoachRouter from "./screen-coach";

const router: IRouter = Router();

router.use(healthRouter);
router.use(projectsRouter);
router.use(dashboardRouter);
router.use(forgeRouter);
router.use(extrasRouter);
router.use(paymentsRouter);
router.use(flintRouter);
router.use(moonIntegrationRouter);
router.use(deployRouter);
router.use(githubRouter);
router.use(gitlabRouter);
router.use(bitbucketRouter);
router.use(secretsRouter);
router.use(adminRouter);
router.use(connectionsRouter);
router.use(coolifyRouter);
router.use(monitorRouter);
router.use(computerAdvisorRouter);
router.use(screenCoachRouter);

export default router;
