import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import dashboardRouter from "./dashboard";
import forgeRouter from "./forge";
import extrasRouter from "./extras";
import paymentsRouter from "./payments";
import flintRouter from "./flint";
import moonIntegrationRouter from "./moonIntegration";
import deployRouter from "./deploy";
import githubRouter from "./github";
import gitlabRouter from "./gitlab";
import bitbucketRouter from "./bitbucket";
import { router as secretsRouter } from "./secrets";
import { router as adminRouter } from "./admin";
import connectionsRouter from "./connections";
import coolifyRouter from "./coolify";
import monitorRouter from "./monitor";
import computerAdvisorRouter from "./computer-advisor";
import screenCoachRouter from "./screen-coach";
import quotaRouter from "./quota";
import siteForgeRouter from "./site-forge";
import landingForgeRouter from "./landing-forge";
import computerFixRouter from "./computer-fix";
import { remoteRouter } from "./remote";
import workspaceRouter from "./workspace";
import ttsRouter from "./tts";
import antivirusRouter from "./antivirus";
import mailboxRouter from "./mailbox";
import emailInboundRouter from "./email-inbound";
import accountRouter from "./account";
import chatHistoryRouter from "./chatHistory";
import promptsRouter from "./prompts";
import moonUsageRouter from "./moonUsage";
import shareRouter from "./share";
import workspaceSearchRouter from "./workspaceSearch";
import forgeReportRouter from "./forgeReport";

const router: IRouter = Router();

router.use(healthRouter);
router.use(projectsRouter);
router.use(dashboardRouter);
router.use(forgeRouter);
router.use(extrasRouter);
router.use(paymentsRouter);
router.use(flintRouter);
router.use(moonIntegrationRouter);
router.use(deployRouter);
router.use(githubRouter);
router.use(gitlabRouter);
router.use(bitbucketRouter);
router.use(secretsRouter);
router.use(adminRouter);
router.use(connectionsRouter);
router.use(coolifyRouter);
router.use(monitorRouter);
router.use(computerAdvisorRouter);
router.use(screenCoachRouter);
router.use(quotaRouter);
router.use(siteForgeRouter);
router.use(landingForgeRouter);
router.use(computerFixRouter);
router.use("/remote", remoteRouter);
router.use(workspaceRouter);
router.use(ttsRouter);
router.use(antivirusRouter);
router.use(mailboxRouter);
router.use(emailInboundRouter);
router.use(accountRouter);
router.use(chatHistoryRouter);
router.use(promptsRouter);
router.use(moonUsageRouter);
router.use(shareRouter);
router.use(workspaceSearchRouter);
router.use(forgeReportRouter);

export default router;
